<?php

return [
    'AF' => ['name' => 'Afghanistan', 'phoneCode' => '+93', 'flagEmoji' => '🇦🇫'],
    'AX' => ['name' => 'Aland Islands', 'phoneCode' => '+358', 'flagEmoji' => '🇦🇽'],
    'AL' => ['name' => 'Albania', 'phoneCode' => '+355', 'flagEmoji' => '🇦🇱'],
    'DZ' => ['name' => 'Algeria', 'phoneCode' => '+213', 'flagEmoji' => '🇩🇿'],
    'AS' => ['name' => 'AmericanSamoa', 'phoneCode' => '+1684', 'flagEmoji' => '🇦🇸'],
    'AD' => ['name' => 'Andorra', 'phoneCode' => '+376', 'flagEmoji' => '🇦🇩'],
    'AO' => ['name' => 'Angola', 'phoneCode' => '+244', 'flagEmoji' => '🇦🇴'],
    'AI' => ['name' => 'Anguilla', 'phoneCode' => '+1264', 'flagEmoji' => '🇦🇮'],
    'AQ' => ['name' => 'Antarctica', 'phoneCode' => '+672', 'flagEmoji' => '🇦🇶'],
    'AG' => ['name' => 'Antigua and Barbuda', 'phoneCode' => '+1268', 'flagEmoji' => '🇦🇬'],
    'AR' => ['name' => 'Argentina', 'phoneCode' => '+54', 'flagEmoji' => '🇦🇷'],
    'AM' => ['name' => 'Armenia', 'phoneCode' => '+374', 'flagEmoji' => '🇦🇲'],
    'AW' => ['name' => 'Aruba', 'phoneCode' => '+297', 'flagEmoji' => '🇦🇼'],
    'AU' => ['name' => 'Australia', 'phoneCode' => '+61', 'flagEmoji' => '🇦🇺'],
    'AT' => ['name' => 'Austria', 'phoneCode' => '+43', 'flagEmoji' => '🇦🇹'],
    'AZ' => ['name' => 'Azerbaijan', 'phoneCode' => '+994', 'flagEmoji' => '🇦🇿'],
    'BS' => ['name' => 'Bahamas', 'phoneCode' => '+1242', 'flagEmoji' => '🇧🇸'],
    'BH' => ['name' => 'Bahrain', 'phoneCode' => '+973', 'flagEmoji' => '🇧🇭'],
    'BD' => ['name' => 'Bangladesh', 'phoneCode' => '+880', 'flagEmoji' => '🇧🇩'],
    'BB' => ['name' => 'Barbados', 'phoneCode' => '+1246', 'flagEmoji' => '🇧🇧'],
    'BY' => ['name' => 'Belarus', 'phoneCode' => '+375', 'flagEmoji' => '🇧🇾'],
    'BE' => ['name' => 'Belgium', 'phoneCode' => '+32', 'flagEmoji' => '🇧🇪'],
    'BZ' => ['name' => 'Belize', 'phoneCode' => '+501', 'flagEmoji' => '🇧🇿'],
    'BJ' => ['name' => 'Benin', 'phoneCode' => '+229', 'flagEmoji' => '🇧🇯'],
    'BM' => ['name' => 'Bermuda', 'phoneCode' => '+1441', 'flagEmoji' => '🇧🇲'],
    'BT' => ['name' => 'Bhutan', 'phoneCode' => '+975', 'flagEmoji' => '🇧🇹'],
    'BO' => ['name' => 'Bolivia, Plurinational State of', 'phoneCode' => '+591', 'flagEmoji' => '🇧🇴'],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'phoneCode' => '+387', 'flagEmoji' => '🇧🇦'],
    'BW' => ['name' => 'Botswana', 'phoneCode' => '+267', 'flagEmoji' => '🇧🇼'],
    'BR' => ['name' => 'Brazil', 'phoneCode' => '+55', 'flagEmoji' => '🇧🇷'],
    'IO' => ['name' => 'British Indian Ocean Territory', 'phoneCode' => '+246', 'flagEmoji' => '🇮🇴'],
    'BN' => ['name' => 'Brunei Darussalam', 'phoneCode' => '+673', 'flagEmoji' => '🇧🇳'],
    'BG' => ['name' => 'Bulgaria', 'phoneCode' => '+359', 'flagEmoji' => '🇧🇬'],
    'BF' => ['name' => 'Burkina Faso', 'phoneCode' => '+226', 'flagEmoji' => '🇧🇫'],
    'BI' => ['name' => 'Burundi', 'phoneCode' => '+257', 'flagEmoji' => '🇧🇮'],
    'KH' => ['name' => 'Cambodia', 'phoneCode' => '+855', 'flagEmoji' => '🇰🇭'],
    'CM' => ['name' => 'Cameroon', 'phoneCode' => '+237', 'flagEmoji' => '🇨🇲'],
    'CA' => ['name' => 'Canada', 'phoneCode' => '+1', 'flagEmoji' => '🇨🇦'],
    'CV' => ['name' => 'Cape Verde', 'phoneCode' => '+238', 'flagEmoji' => '🇨🇻'],
    'KY' => ['name' => 'Cayman Islands', 'phoneCode' => '+345', 'flagEmoji' => '🇰🇾'],
    'CF' => ['name' => 'Central African Republic', 'phoneCode' => '+236', 'flagEmoji' => '🇨🇫'],
    'TD' => ['name' => 'Chad', 'phoneCode' => '+235', 'flagEmoji' => '🇹🇩'],
    'CL' => ['name' => 'Chile', 'phoneCode' => '+56', 'flagEmoji' => '🇨🇱'],
    'CN' => ['name' => 'China', 'phoneCode' => '+86', 'flagEmoji' => '🇨🇳'],
    'CX' => ['name' => 'Christmas Island', 'phoneCode' => '+61', 'flagEmoji' => '🇨🇽'],
    'CC' => ['name' => 'Cocos (Keeling) Islands', 'phoneCode' => '+61', 'flagEmoji' => '🇨🇨'],
    'CO' => ['name' => 'Colombia', 'phoneCode' => '+57', 'flagEmoji' => '🇨🇴'],
    'KM' => ['name' => 'Comoros', 'phoneCode' => '+269', 'flagEmoji' => '🇰🇲'],
    'CG' => ['name' => 'Congo', 'phoneCode' => '+242', 'flagEmoji' => '🇨🇬'],
    'CD' => ['name' => 'Congo, The Democratic Republic of the Congo', 'phoneCode' => '+243', 'flagEmoji' => '🇨🇩'],
    'CK' => ['name' => 'Cook Islands', 'phoneCode' => '+682', 'flagEmoji' => '🇨🇰'],
    'CR' => ['name' => 'Costa Rica', 'phoneCode' => '+506', 'flagEmoji' => '🇨🇷'],
    'CI' => ['name' => 'Cote d\'Ivoire', 'phoneCode' => '+225', 'flagEmoji' => '🇨🇮'],
    'HR' => ['name' => 'Croatia', 'phoneCode' => '+385', 'flagEmoji' => '🇭🇷'],
    'CU' => ['name' => 'Cuba', 'phoneCode' => '+53', 'flagEmoji' => '🇨🇺'],
    'CY' => ['name' => 'Cyprus', 'phoneCode' => '+357', 'flagEmoji' => '🇨🇾'],
    'CZ' => ['name' => 'Czech Republic', 'phoneCode' => '+420', 'flagEmoji' => '🇨🇿'],
    'DK' => ['name' => 'Denmark', 'phoneCode' => '+45', 'flagEmoji' => '🇩🇰'],
    'DJ' => ['name' => 'Djibouti', 'phoneCode' => '+253', 'flagEmoji' => '🇩🇯'],
    'DM' => ['name' => 'Dominica', 'phoneCode' => '+1767', 'flagEmoji' => '🇩🇲'],
    'DO' => ['name' => 'Dominican Republic', 'phoneCode' => '+1849', 'flagEmoji' => '🇩🇴'],
    'EC' => ['name' => 'Ecuador', 'phoneCode' => '+593', 'flagEmoji' => '🇪🇨'],
    'EG' => ['name' => 'Egypt', 'phoneCode' => '+20', 'flagEmoji' => '🇪🇬'],
    'SV' => ['name' => 'El Salvador', 'phoneCode' => '+503', 'flagEmoji' => '🇸🇻'],
    'GQ' => ['name' => 'Equatorial Guinea', 'phoneCode' => '+240', 'flagEmoji' => '🇬🇶'],
    'ER' => ['name' => 'Eritrea', 'phoneCode' => '+291', 'flagEmoji' => '🇪🇷'],
    'EE' => ['name' => 'Estonia', 'phoneCode' => '+372', 'flagEmoji' => '🇪🇪'],
    'ET' => ['name' => 'Ethiopia', 'phoneCode' => '+251', 'flagEmoji' => '🇪🇹'],
    'FK' => ['name' => 'Falkland Islands (Malvinas)', 'phoneCode' => '+500', 'flagEmoji' => '🇫🇰'],
    'FO' => ['name' => 'Faroe Islands', 'phoneCode' => '+298', 'flagEmoji' => '🇫🇴'],
    'FJ' => ['name' => 'Fiji', 'phoneCode' => '+679', 'flagEmoji' => '🇫🇯'],
    'FI' => ['name' => 'Finland', 'phoneCode' => '+358', 'flagEmoji' => '🇫🇮'],
    'FR' => ['name' => 'France', 'phoneCode' => '+33', 'flagEmoji' => '🇫🇷'],
    'GF' => ['name' => 'French Guiana', 'phoneCode' => '+594', 'flagEmoji' => '🇬🇫'],
    'PF' => ['name' => 'French Polynesia', 'phoneCode' => '+689', 'flagEmoji' => '🇵🇫'],
    'GA' => ['name' => 'Gabon', 'phoneCode' => '+241', 'flagEmoji' => '🇬🇦'],
    'GM' => ['name' => 'Gambia', 'phoneCode' => '+220', 'flagEmoji' => '🇬🇲'],
    'GE' => ['name' => 'Georgia', 'phoneCode' => '+995', 'flagEmoji' => '🇬🇪'],
    'DE' => ['name' => 'Germany', 'phoneCode' => '+49', 'flagEmoji' => '🇩🇪'],
    'GH' => ['name' => 'Ghana', 'phoneCode' => '+233', 'flagEmoji' => '🇬🇭'],
    'GI' => ['name' => 'Gibraltar', 'phoneCode' => '+350', 'flagEmoji' => '🇬🇮'],
    'GR' => ['name' => 'Greece', 'phoneCode' => '+30', 'flagEmoji' => '🇬🇷'],
    'GL' => ['name' => 'Greenland', 'phoneCode' => '+299', 'flagEmoji' => '🇬🇱'],
    'GD' => ['name' => 'Grenada', 'phoneCode' => '+1473', 'flagEmoji' => '🇬🇩'],
    'GP' => ['name' => 'Guadeloupe', 'phoneCode' => '+590', 'flagEmoji' => '🇬🇵'],
    'GU' => ['name' => 'Guam', 'phoneCode' => '+1671', 'flagEmoji' => '🇬🇺'],
    'GT' => ['name' => 'Guatemala', 'phoneCode' => '+502', 'flagEmoji' => '🇬🇹'],
    'GG' => ['name' => 'Guernsey', 'phoneCode' => '+44', 'flagEmoji' => '🇬🇬'],
    'GN' => ['name' => 'Guinea', 'phoneCode' => '+224', 'flagEmoji' => '🇬🇳'],
    'GW' => ['name' => 'Guinea-Bissau', 'phoneCode' => '+245', 'flagEmoji' => '🇬🇼'],
    'GY' => ['name' => 'Guyana', 'phoneCode' => '+595', 'flagEmoji' => '🇬🇾'],
    'HT' => ['name' => 'Haiti', 'phoneCode' => '+509', 'flagEmoji' => '🇭🇹'],
    'VA' => ['name' => 'Holy See (Vatican City State)', 'phoneCode' => '+379', 'flagEmoji' => '🇻🇦'],
    'HN' => ['name' => 'Honduras', 'phoneCode' => '+504', 'flagEmoji' => '🇭🇳'],
    'HK' => ['name' => 'Hong Kong', 'phoneCode' => '+852', 'flagEmoji' => '🇭🇰'],
    'HU' => ['name' => 'Hungary', 'phoneCode' => '+36', 'flagEmoji' => '🇭🇺'],
    'IS' => ['name' => 'Iceland', 'phoneCode' => '+354', 'flagEmoji' => '🇮🇸'],
    'IN' => ['name' => 'India', 'phoneCode' => '+91', 'flagEmoji' => '🇮🇳'],
    'ID' => ['name' => 'Indonesia', 'phoneCode' => '+62', 'flagEmoji' => '🇮🇩'],
    'IR' => ['name' => 'Iran, Islamic Republic of Persian Gulf', 'phoneCode' => '+98', 'flagEmoji' => '🇮🇷'],
    'IQ' => ['name' => 'Iraq', 'phoneCode' => '+964', 'flagEmoji' => '🇮🇶'],
    'IE' => ['name' => 'Ireland', 'phoneCode' => '+353', 'flagEmoji' => '🇮🇪'],
    'IM' => ['name' => 'Isle of Man', 'phoneCode' => '+44', 'flagEmoji' => '🇮🇲'],
    'IL' => ['name' => 'Israel', 'phoneCode' => '+972', 'flagEmoji' => '🇮🇱'],
    'IT' => ['name' => 'Italy', 'phoneCode' => '+39', 'flagEmoji' => '🇮🇹'],
    'JM' => ['name' => 'Jamaica', 'phoneCode' => '+1876', 'flagEmoji' => '🇯🇲'],
    'JP' => ['name' => 'Japan', 'phoneCode' => '+81', 'flagEmoji' => '🇯🇵'],
    'JE' => ['name' => 'Jersey', 'phoneCode' => '+44', 'flagEmoji' => '🇯🇪'],
    'JO' => ['name' => 'Jordan', 'phoneCode' => '+962', 'flagEmoji' => '🇯🇴'],
    'KZ' => ['name' => 'Kazakhstan', 'phoneCode' => '+77', 'flagEmoji' => '🇰🇿'],
    'KE' => ['name' => 'Kenya', 'phoneCode' => '+254', 'flagEmoji' => '🇰🇪'],
    'KI' => ['name' => 'Kiribati', 'phoneCode' => '+686', 'flagEmoji' => '🇰🇮'],
    'KP' => ['name' => 'Korea, Democratic People\'s Republic of Korea', 'phoneCode' => '+850', 'flagEmoji' => '🇰🇵'],
    'KR' => ['name' => 'Korea, Republic of South Korea', 'phoneCode' => '+82', 'flagEmoji' => '🇰🇷'],
    'KW' => ['name' => 'Kuwait', 'phoneCode' => '+965', 'flagEmoji' => '🇰🇼'],
    'KG' => ['name' => 'Kyrgyzstan', 'phoneCode' => '+996', 'flagEmoji' => '🇰🇬'],
    'LA' => ['name' => 'Laos', 'phoneCode' => '+856', 'flagEmoji' => '🇱🇦'],
    'LV' => ['name' => 'Latvia', 'phoneCode' => '+371', 'flagEmoji' => '🇱🇻'],
    'LB' => ['name' => 'Lebanon', 'phoneCode' => '+961', 'flagEmoji' => '🇱🇧'],
    'LS' => ['name' => 'Lesotho', 'phoneCode' => '+266', 'flagEmoji' => '🇱🇸'],
    'LR' => ['name' => 'Liberia', 'phoneCode' => '+231', 'flagEmoji' => '🇱🇷'],
    'LY' => ['name' => 'Libyan Arab Jamahiriya', 'phoneCode' => '+218', 'flagEmoji' => '🇱🇾'],
    'LI' => ['name' => 'Liechtenstein', 'phoneCode' => '+423', 'flagEmoji' => '🇱🇮'],
    'LT' => ['name' => 'Lithuania', 'phoneCode' => '+370', 'flagEmoji' => '🇱🇹'],
    'LU' => ['name' => 'Luxembourg', 'phoneCode' => '+352', 'flagEmoji' => '🇱🇺'],
    'MO' => ['name' => 'Macao', 'phoneCode' => '+853', 'flagEmoji' => '🇲🇴'],
    'MK' => ['name' => 'Macedonia', 'phoneCode' => '+389', 'flagEmoji' => '🇲🇰'],
    'MG' => ['name' => 'Madagascar', 'phoneCode' => '+261', 'flagEmoji' => '🇲🇬'],
    'MW' => ['name' => 'Malawi', 'phoneCode' => '+265', 'flagEmoji' => '🇲🇼'],
    'MY' => ['name' => 'Malaysia', 'phoneCode' => '+60', 'flagEmoji' => '🇲🇾'],
    'MV' => ['name' => 'Maldives', 'phoneCode' => '+960', 'flagEmoji' => '🇲🇻'],
    'ML' => ['name' => 'Mali', 'phoneCode' => '+223', 'flagEmoji' => '🇲🇱'],
    'MT' => ['name' => 'Malta', 'phoneCode' => '+356', 'flagEmoji' => '🇲🇹'],
    'MH' => ['name' => 'Marshall Islands', 'phoneCode' => '+692', 'flagEmoji' => '🇲🇭'],
    'MQ' => ['name' => 'Martinique', 'phoneCode' => '+596', 'flagEmoji' => '🇲🇶'],
    'MR' => ['name' => 'Mauritania', 'phoneCode' => '+222', 'flagEmoji' => '🇲🇷'],
    'MU' => ['name' => 'Mauritius', 'phoneCode' => '+230', 'flagEmoji' => '🇲🇺'],
    'YT' => ['name' => 'Mayotte', 'phoneCode' => '+262', 'flagEmoji' => '🇾🇹'],
    'MX' => ['name' => 'Mexico', 'phoneCode' => '+52', 'flagEmoji' => '🇲🇽'],
    'FM' => ['name' => 'Micronesia, Federated States of Micronesia', 'phoneCode' => '+691', 'flagEmoji' => '🇫🇲'],
    'MD' => ['name' => 'Moldova', 'phoneCode' => '+373', 'flagEmoji' => '🇲🇩'],
    'MC' => ['name' => 'Monaco', 'phoneCode' => '+377', 'flagEmoji' => '🇲🇨'],
    'MN' => ['name' => 'Mongolia', 'phoneCode' => '+976', 'flagEmoji' => '🇲🇳'],
    'ME' => ['name' => 'Montenegro', 'phoneCode' => '+382', 'flagEmoji' => '🇲🇪'],
    'MS' => ['name' => 'Montserrat', 'phoneCode' => '+1664', 'flagEmoji' => '🇲🇸'],
    'MA' => ['name' => 'Morocco', 'phoneCode' => '+212', 'flagEmoji' => '🇲🇦'],
    'MZ' => ['name' => 'Mozambique', 'phoneCode' => '+258', 'flagEmoji' => '🇲🇿'],
    'MM' => ['name' => 'Myanmar', 'phoneCode' => '+95', 'flagEmoji' => '🇲🇲'],
    'NA' => ['name' => 'Namibia', 'phoneCode' => '+264', 'flagEmoji' => '🇳🇦'],
    'NR' => ['name' => 'Nauru', 'phoneCode' => '+674', 'flagEmoji' => '🇳🇷'],
    'NP' => ['name' => 'Nepal', 'phoneCode' => '+977', 'flagEmoji' => '🇳🇵'],
    'NL' => ['name' => 'Netherlands', 'phoneCode' => '+31', 'flagEmoji' => '🇳🇱'],
    'AN' => ['name' => 'Netherlands Antilles', 'phoneCode' => '+599', 'flagEmoji' => '🇧🇶'],
    'NC' => ['name' => 'New Caledonia', 'phoneCode' => '+687', 'flagEmoji' => '🇳🇨'],
    'NZ' => ['name' => 'New Zealand', 'phoneCode' => '+64', 'flagEmoji' => '🇳🇿'],
    'NI' => ['name' => 'Nicaragua', 'phoneCode' => '+505', 'flagEmoji' => '🇳🇮'],
    'NE' => ['name' => 'Niger', 'phoneCode' => '+227', 'flagEmoji' => '🇳🇪'],
    'NG' => ['name' => 'Nigeria', 'phoneCode' => '+234', 'flagEmoji' => '🇳🇬'],
    'NU' => ['name' => 'Niue', 'phoneCode' => '+683', 'flagEmoji' => '🇳🇺'],
    'NF' => ['name' => 'Norfolk Island', 'phoneCode' => '+672', 'flagEmoji' => '🇳🇫'],
    'MP' => ['name' => 'Northern Mariana Islands', 'phoneCode' => '+1670', 'flagEmoji' => '🇲🇵'],
    'NO' => ['name' => 'Norway', 'phoneCode' => '+47', 'flagEmoji' => '🇳🇴'],
    'OM' => ['name' => 'Oman', 'phoneCode' => '+968', 'flagEmoji' => '🇴🇲'],
    'PK' => ['name' => 'Pakistan', 'phoneCode' => '+92', 'flagEmoji' => '🇵🇰'],
    'PW' => ['name' => 'Palau', 'phoneCode' => '+680', 'flagEmoji' => '🇵🇼'],
    'PS' => ['name' => 'Palestinian Territory, Occupied', 'phoneCode' => '+970', 'flagEmoji' => '🇵🇸'],
    'PA' => ['name' => 'Panama', 'phoneCode' => '+507', 'flagEmoji' => '🇵🇦'],
    'PG' => ['name' => 'Papua New Guinea', 'phoneCode' => '+675', 'flagEmoji' => '🇵🇬'],
    'PY' => ['name' => 'Paraguay', 'phoneCode' => '+595', 'flagEmoji' => '🇵🇾'],
    'PE' => ['name' => 'Peru', 'phoneCode' => '+51', 'flagEmoji' => '🇵🇪'],
    'PH' => ['name' => 'Philippines', 'phoneCode' => '+63', 'flagEmoji' => '🇵🇭'],
    'PN' => ['name' => 'Pitcairn', 'phoneCode' => '+872', 'flagEmoji' => '🇵🇳'],
    'PL' => ['name' => 'Poland', 'phoneCode' => '+48', 'flagEmoji' => '🇵🇱'],
    'PT' => ['name' => 'Portugal', 'phoneCode' => '+351', 'flagEmoji' => '🇵🇹'],
    'PR' => ['name' => 'Puerto Rico', 'phoneCode' => '+1939', 'flagEmoji' => '🇵🇷'],
    'QA' => ['name' => 'Qatar', 'phoneCode' => '+974', 'flagEmoji' => '🇶🇦'],
    'RE' => ['name' => 'Reunion', 'phoneCode' => '+262', 'flagEmoji' => '🇷🇪'],
    'RO' => ['name' => 'Romania', 'phoneCode' => '+40', 'flagEmoji' => '🇷🇴'],
    'RU' => ['name' => 'Russia', 'phoneCode' => '+7', 'flagEmoji' => '🇷🇺'],
    'RW' => ['name' => 'Rwanda', 'phoneCode' => '+250', 'flagEmoji' => '🇷🇼'],
    'BL' => ['name' => 'Saint Barthelemy', 'phoneCode' => '+590', 'flagEmoji' => '🇧🇱'],
    'SH' => ['name' => 'Saint Helena, Ascension and Tristan Da Cunha', 'phoneCode' => '+290', 'flagEmoji' => '🇸🇭'],
    'KN' => ['name' => 'Saint Kitts and Nevis', 'phoneCode' => '+1869', 'flagEmoji' => '🇰🇳'],
    'LC' => ['name' => 'Saint Lucia', 'phoneCode' => '+1758', 'flagEmoji' => '🇱🇨'],
    'MF' => ['name' => 'Saint Martin', 'phoneCode' => '+590', 'flagEmoji' => '🇲🇫'],
    'PM' => ['name' => 'Saint Pierre and Miquelon', 'phoneCode' => '+508', 'flagEmoji' => '🇵🇲'],
    'VC' => ['name' => 'Saint Vincent and the Grenadines', 'phoneCode' => '+1784', 'flagEmoji' => '🇻🇨'],
    'WS' => ['name' => 'Samoa', 'phoneCode' => '+685', 'flagEmoji' => '🇼🇸'],
    'SM' => ['name' => 'San Marino', 'phoneCode' => '+378', 'flagEmoji' => '🇸🇲'],
    'ST' => ['name' => 'Sao Tome and Principe', 'phoneCode' => '+239', 'flagEmoji' => '🇸🇹'],
    'SA' => ['name' => 'Saudi Arabia', 'phoneCode' => '+966', 'flagEmoji' => '🇸🇦'],
    'SN' => ['name' => 'Senegal', 'phoneCode' => '+221', 'flagEmoji' => '🇸🇳'],
    'RS' => ['name' => 'Serbia', 'phoneCode' => '+381', 'flagEmoji' => '🇷🇸'],
    'SC' => ['name' => 'Seychelles', 'phoneCode' => '+248', 'flagEmoji' => '🇸🇨'],
    'SL' => ['name' => 'Sierra Leone', 'phoneCode' => '+232', 'flagEmoji' => '🇸🇱'],
    'SG' => ['name' => 'Singapore', 'phoneCode' => '+65', 'flagEmoji' => '🇸🇬'],
    'SK' => ['name' => 'Slovakia', 'phoneCode' => '+421', 'flagEmoji' => '🇸🇰'],
    'SI' => ['name' => 'Slovenia', 'phoneCode' => '+386', 'flagEmoji' => '🇸🇮'],
    'SB' => ['name' => 'Solomon Islands', 'phoneCode' => '+677', 'flagEmoji' => '🇸🇧'],
    'SO' => ['name' => 'Somalia', 'phoneCode' => '+252', 'flagEmoji' => '🇸🇴'],
    'ZA' => ['name' => 'South Africa', 'phoneCode' => '+27', 'flagEmoji' => '🇿🇦'],
    'GS' => ['name' => 'South Georgia and the South Sandwich Islands', 'phoneCode' => '+500', 'flagEmoji' => '🇬🇸'],
    'SS' => ['name' => 'South Sudan', 'phoneCode' => '+211', 'flagEmoji' => '🇸🇸'],
    'ES' => ['name' => 'Spain', 'phoneCode' => '+34', 'flagEmoji' => '🇪🇸'],
    'LK' => ['name' => 'Sri Lanka', 'phoneCode' => '+94', 'flagEmoji' => '🇱🇰'],
    'SD' => ['name' => 'Sudan', 'phoneCode' => '+249', 'flagEmoji' => '🇸🇩'],
    'SR' => ['name' => 'Suriname', 'phoneCode' => '+597', 'flagEmoji' => '🇸🇷'],
    'SJ' => ['name' => 'Svalbard and Jan Mayen', 'phoneCode' => '+47', 'flagEmoji' => '🇸🇯'],
    'SZ' => ['name' => 'Swaziland', 'phoneCode' => '+268', 'flagEmoji' => '🇸🇿'],
    'SE' => ['name' => 'Sweden', 'phoneCode' => '+46', 'flagEmoji' => '🇸🇪'],
    'CH' => ['name' => 'Switzerland', 'phoneCode' => '+41', 'flagEmoji' => '🇨🇭'],
    'SY' => ['name' => 'Syrian Arab Republic', 'phoneCode' => '+963', 'flagEmoji' => '🇸🇾'],
    'TW' => ['name' => 'Taiwan', 'phoneCode' => '+886', 'flagEmoji' => '🇹🇼'],
    'TJ' => ['name' => 'Tajikistan', 'phoneCode' => '+992', 'flagEmoji' => '🇹🇯'],
    'TZ' => ['name' => 'Tanzania, United Republic of Tanzania', 'phoneCode' => '+255', 'flagEmoji' => '🇹🇿'],
    'TH' => ['name' => 'Thailand', 'phoneCode' => '+66', 'flagEmoji' => '🇹🇭'],
    'TL' => ['name' => 'Timor-Leste', 'phoneCode' => '+670', 'flagEmoji' => '🇹🇱'],
    'TG' => ['name' => 'Togo', 'phoneCode' => '+228', 'flagEmoji' => '🇹🇬'],
    'TK' => ['name' => 'Tokelau', 'phoneCode' => '+690', 'flagEmoji' => '🇹🇰'],
    'TO' => ['name' => 'Tonga', 'phoneCode' => '+676', 'flagEmoji' => '🇹🇴'],
    'TT' => ['name' => 'Trinidad and Tobago', 'phoneCode' => '+1868', 'flagEmoji' => '🇹🇹'],
    'TN' => ['name' => 'Tunisia', 'phoneCode' => '+216', 'flagEmoji' => '🇹🇳'],
    'TR' => ['name' => 'Turkey', 'phoneCode' => '+90', 'flagEmoji' => '🇹🇷'],
    'TM' => ['name' => 'Turkmenistan', 'phoneCode' => '+993', 'flagEmoji' => '🇹🇲'],
    'TC' => ['name' => 'Turks and Caicos Islands', 'phoneCode' => '+1649', 'flagEmoji' => '🇹🇨'],
    'TV' => ['name' => 'Tuvalu', 'phoneCode' => '+688', 'flagEmoji' => '🇹🇻'],
    'UG' => ['name' => 'Uganda', 'phoneCode' => '+256', 'flagEmoji' => '🇺🇬'],
    'UA' => ['name' => 'Ukraine', 'phoneCode' => '+380', 'flagEmoji' => '🇺🇦'],
    'AE' => ['name' => 'United Arab Emirates', 'phoneCode' => '+971', 'flagEmoji' => '🇦🇪'],
    'GB' => ['name' => 'United Kingdom', 'phoneCode' => '+44', 'flagEmoji' => '🇬🇧'],
    'US' => ['name' => 'United States', 'phoneCode' => '+1', 'flagEmoji' => '🇺🇸'],
    'UY' => ['name' => 'Uruguay', 'phoneCode' => '+598', 'flagEmoji' => '🇺🇾'],
    'UZ' => ['name' => 'Uzbekistan', 'phoneCode' => '+998', 'flagEmoji' => '🇺🇿'],
    'VU' => ['name' => 'Vanuatu', 'phoneCode' => '+678', 'flagEmoji' => '🇻🇺'],
    'VE' => ['name' => 'Venezuela, Bolivarian Republic of Venezuela', 'phoneCode' => '+58', 'flagEmoji' => '🇻🇪'],
    'VN' => ['name' => 'Vietnam', 'phoneCode' => '+84', 'flagEmoji' => '🇻🇳'],
    'VG' => ['name' => 'Virgin Islands, British', 'phoneCode' => '+1284', 'flagEmoji' => '🇻🇬'],
    'VI' => ['name' => 'Virgin Islands, U.S.', 'phoneCode' => '+1340', 'flagEmoji' => '🇻🇮'],
    'WF' => ['name' => 'Wallis and Futuna', 'phoneCode' => '+681', 'flagEmoji' => '🇼🇫'],
    'YE' => ['name' => 'Yemen', 'phoneCode' => '+967', 'flagEmoji' => '🇾🇪'],
    'ZM' => ['name' => 'Zambia', 'phoneCode' => '+260', 'flagEmoji' => '🇿🇲'],
    'ZW' => ['name' => 'Zimbabwe', 'phoneCode' => '+263', 'flagEmoji' => '🇿🇼'],
];