<?php

namespace Modules\AppQRCodes\Support;

class QrStyleTemplateCatalog
{
    public static function all(): array
    {
        return [
            'clean_card' => [
                'label' => __('Default QR'),
                'description' => __('Plain QR only, no frame or sticker design.'),
                'pattern' => 'square',
                'foreground' => '#0f172a',
                'background' => '#ffffff',
                'fallback' => '#0f172a',
                'shape' => 'square',
                'accent' => '#2563eb',
                'surface' => '#ffffff',
            ],
            'rounded_gradient' => [
                'label' => __('Rounded gradient'),
                'description' => __('Rounded modules with gradient color and branded finder corners.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#b02a2a',
                'background' => '#ffffff',
                'fallback' => '#264653',
                'shape' => 'rounded',
                'accent' => '#2a9d8f',
                'surface' => '#ffffff',
            ],
            'roundness_sunset' => [
                'label' => __('Sunset round'),
                'description' => __('Warm red-orange rounded modules for retail campaigns.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#be123c',
                'background' => '#fff7ed',
                'fallback' => '#f97316',
                'shape' => 'rounded',
                'accent' => '#0f766e',
                'surface' => '#fff1f2',
            ],
            'roundness_ocean' => [
                'label' => __('Ocean round'),
                'description' => __('Blue to teal rounded QR with deep finder dots.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#1d4ed8',
                'background' => '#eff6ff',
                'fallback' => '#06b6d4',
                'shape' => 'rounded',
                'accent' => '#0e7490',
                'surface' => '#ecfeff',
            ],
            'roundness_forest' => [
                'label' => __('Forest round'),
                'description' => __('Green gradient rounded QR for stores and menus.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#15803d',
                'background' => '#f0fdf4',
                'fallback' => '#84cc16',
                'shape' => 'rounded',
                'accent' => '#047857',
                'surface' => '#dcfce7',
            ],
            'roundness_berry' => [
                'label' => __('Berry round'),
                'description' => __('Pink and violet rounded QR for creator campaigns.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#be185d',
                'background' => '#fff1f8',
                'fallback' => '#7c3aed',
                'shape' => 'rounded',
                'accent' => '#db2777',
                'surface' => '#fce7f3',
            ],
            'roundness_indigo' => [
                'label' => __('Indigo round'),
                'description' => __('Clean indigo gradient with modern blue finder corners.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#4338ca',
                'background' => '#eef2ff',
                'fallback' => '#0ea5e9',
                'shape' => 'rounded',
                'accent' => '#2563eb',
                'surface' => '#e0e7ff',
            ],
            'roundness_lime' => [
                'label' => __('Lime round'),
                'description' => __('Fresh lime and emerald rounded QR for wellness brands.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#65a30d',
                'background' => '#f7fee7',
                'fallback' => '#10b981',
                'shape' => 'rounded',
                'accent' => '#16a34a',
                'surface' => '#ecfccb',
            ],
            'roundness_carbon' => [
                'label' => __('Carbon round'),
                'description' => __('Dark graphite modules with steel finder corners.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#111827',
                'background' => '#f8fafc',
                'fallback' => '#64748b',
                'shape' => 'rounded',
                'accent' => '#334155',
                'surface' => '#e2e8f0',
            ],
            'roundness_gold' => [
                'label' => __('Gold round'),
                'description' => __('Gold and amber gradient for premium printed assets.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#92400e',
                'background' => '#fffbeb',
                'fallback' => '#f59e0b',
                'shape' => 'rounded',
                'accent' => '#ca8a04',
                'surface' => '#fef3c7',
            ],
            'roundness_candy' => [
                'label' => __('Candy round'),
                'description' => __('Bright coral and cyan gradient with playful corners.'),
                'pattern' => 'gradient_rounded',
                'foreground' => '#ef4444',
                'background' => '#fff1f2',
                'fallback' => '#06b6d4',
                'shape' => 'rounded',
                'accent' => '#ec4899',
                'surface' => '#ffe4e6',
            ],
            'slate_minimal' => [
                'label' => __('Slate minimal'),
                'description' => __('Quiet card with simple border and scan text.'),
                'pattern' => 'square',
                'foreground' => '#111827',
                'background' => '#ffffff',
                'fallback' => '#020617',
                'shape' => 'square',
                'accent' => '#64748b',
                'surface' => '#f8fafc',
            ],
            'navy_label' => [
                'label' => __('Navy square'),
                'description' => __('Navy framed square for print stickers.'),
                'pattern' => 'square',
                'foreground' => '#0f4f87',
                'background' => '#ffffff',
                'fallback' => '#0b2447',
                'shape' => 'square',
                'accent' => '#f97316',
                'surface' => '#0b2447',
            ],
            'coral_sticker' => [
                'label' => __('Coral square'),
                'description' => __('Soft coral square without CTA text.'),
                'pattern' => 'square',
                'foreground' => '#c7265b',
                'background' => '#fff1f4',
                'fallback' => '#9f1239',
                'shape' => 'square',
                'accent' => '#fb7185',
                'surface' => '#fff1f4',
            ],
            'emerald_ring' => [
                'label' => __('Emerald square'),
                'description' => __('Green square frame for storefronts.'),
                'pattern' => 'square',
                'foreground' => '#0f7a32',
                'background' => '#ffffff',
                'fallback' => '#064e3b',
                'shape' => 'square',
                'accent' => '#16a34a',
                'surface' => '#ecfdf5',
            ],
            'gold_orbit' => [
                'label' => __('Gold square'),
                'description' => __('Premium gold square frame.'),
                'pattern' => 'square',
                'foreground' => '#171717',
                'background' => '#fffaf0',
                'fallback' => '#92400e',
                'shape' => 'square',
                'accent' => '#f59e0b',
                'surface' => '#fffbeb',
            ],
            'pink_scan' => [
                'label' => __('Pink square'),
                'description' => __('Retail style pink square.'),
                'pattern' => 'square',
                'foreground' => '#be185d',
                'background' => '#fff1f8',
                'fallback' => '#831843',
                'shape' => 'square',
                'accent' => '#ec4899',
                'surface' => '#fce7f3',
            ],
            'teal_ticket' => [
                'label' => __('Teal square'),
                'description' => __('Teal square layout for offers.'),
                'pattern' => 'square',
                'foreground' => '#0f766e',
                'background' => '#f0fdfa',
                'fallback' => '#134e4a',
                'shape' => 'square',
                'accent' => '#14b8a6',
                'surface' => '#ccfbf1',
            ],
            'black_premium' => [
                'label' => __('Black premium'),
                'description' => __('High contrast luxury frame.'),
                'pattern' => 'square',
                'foreground' => '#111827',
                'background' => '#ffffff',
                'fallback' => '#030712',
                'shape' => 'square',
                'accent' => '#facc15',
                'surface' => '#111827',
            ],
            'orange_file' => [
                'label' => __('Orange square'),
                'description' => __('Document and file sharing square.'),
                'pattern' => 'square',
                'foreground' => '#9a3412',
                'background' => '#fff7ed',
                'fallback' => '#7c2d12',
                'shape' => 'square',
                'accent' => '#f97316',
                'surface' => '#ffedd5',
            ],
            'default_mosaic' => [
                'label' => __('Default Mosaic'),
                'description' => __('Plain mosaic QR with brand-aware dots only.'),
                'pattern' => 'mosaic',
                'foreground' => '#2563eb',
                'background' => '#ffffff',
                'fallback' => '#0f172a',
                'shape' => 'circle',
                'accent' => '#2563eb',
                'surface' => '#ffffff',
            ],
            'purple_badge' => [
                'label' => __('Purple badge'),
                'description' => __('Creator campaign badge.'),
                'pattern' => 'mosaic',
                'foreground' => '#7c3aed',
                'background' => '#faf5ff',
                'fallback' => '#3b0764',
                'shape' => 'circle',
                'accent' => '#a855f7',
                'surface' => '#ede9fe',
            ],
            'green_circle' => [
                'label' => __('Green square'),
                'description' => __('Green eco/event square frame.'),
                'pattern' => 'square',
                'foreground' => '#15803d',
                'background' => '#f7fee7',
                'fallback' => '#14532d',
                'shape' => 'square',
                'accent' => '#84cc16',
                'surface' => '#dcfce7',
            ],
            'blue_coupon' => [
                'label' => __('Blue square'),
                'description' => __('Blue campaign square frame.'),
                'pattern' => 'square',
                'foreground' => '#1d4ed8',
                'background' => '#eff6ff',
                'fallback' => '#1e3a8a',
                'shape' => 'square',
                'accent' => '#3b82f6',
                'surface' => '#dbeafe',
            ],
            'red_event' => [
                'label' => __('Red square'),
                'description' => __('High-energy square for event check-ins.'),
                'pattern' => 'square',
                'foreground' => '#b91c1c',
                'background' => '#fff1f2',
                'fallback' => '#7f1d1d',
                'shape' => 'square',
                'accent' => '#ef4444',
                'surface' => '#fee2e2',
            ],
            'cyan_pass' => [
                'label' => __('Cyan square'),
                'description' => __('Clean cyan square for access and tickets.'),
                'pattern' => 'square',
                'foreground' => '#0e7490',
                'background' => '#ecfeff',
                'fallback' => '#164e63',
                'shape' => 'square',
                'accent' => '#06b6d4',
                'surface' => '#cffafe',
            ],
            'amber_sale' => [
                'label' => __('Amber square'),
                'description' => __('Warm retail square for promotions.'),
                'pattern' => 'square',
                'foreground' => '#92400e',
                'background' => '#fffbeb',
                'fallback' => '#78350f',
                'shape' => 'square',
                'accent' => '#f59e0b',
                'surface' => '#fef3c7',
            ],
            'violet_orbit' => [
                'label' => __('Violet square'),
                'description' => __('Creator square frame with vivid accent.'),
                'pattern' => 'square',
                'foreground' => '#6d28d9',
                'background' => '#faf5ff',
                'fallback' => '#3b0764',
                'shape' => 'square',
                'accent' => '#8b5cf6',
                'surface' => '#ede9fe',
            ],
            'ocean_mosaic' => [
                'label' => __('Ocean mosaic'),
                'description' => __('Blue and teal image-driven QR texture.'),
                'pattern' => 'mosaic',
                'foreground' => '#0284c7',
                'background' => '#ecfeff',
                'fallback' => '#0c4a6e',
                'shape' => 'circle',
                'accent' => '#14b8a6',
                'surface' => '#e0f2fe',
            ],
            'sunset_mosaic' => [
                'label' => __('Sunset mosaic'),
                'description' => __('Warm orange and rose mosaic styling.'),
                'pattern' => 'mosaic',
                'foreground' => '#ea580c',
                'background' => '#fff7ed',
                'fallback' => '#7c2d12',
                'shape' => 'rounded',
                'accent' => '#e11d48',
                'surface' => '#ffedd5',
            ],
            'forest_mosaic' => [
                'label' => __('Forest mosaic'),
                'description' => __('Green brand-image dots for local campaigns.'),
                'pattern' => 'mosaic',
                'foreground' => '#15803d',
                'background' => '#f0fdf4',
                'fallback' => '#14532d',
                'shape' => 'circle',
                'accent' => '#65a30d',
                'surface' => '#dcfce7',
            ],
            'mono_mosaic' => [
                'label' => __('Mono mosaic'),
                'description' => __('Black and grey mosaic for strict brands.'),
                'pattern' => 'mosaic',
                'foreground' => '#111827',
                'background' => '#f8fafc',
                'fallback' => '#020617',
                'shape' => 'square',
                'accent' => '#64748b',
                'surface' => '#e5e7eb',
            ],
            'rose_mosaic' => [
                'label' => __('Rose mosaic'),
                'description' => __('Pink creator mosaic with soft background.'),
                'pattern' => 'mosaic',
                'foreground' => '#be185d',
                'background' => '#fff1f8',
                'fallback' => '#831843',
                'shape' => 'rounded',
                'accent' => '#f472b6',
                'surface' => '#fce7f3',
            ],
            'neon_mosaic' => [
                'label' => __('Neon mosaic'),
                'description' => __('Electric green and cyan dots for bold campaigns.'),
                'pattern' => 'mosaic',
                'foreground' => '#00c853',
                'background' => '#ecfeff',
                'fallback' => '#052e16',
                'shape' => 'circle',
                'accent' => '#06b6d4',
                'surface' => '#d1fae5',
            ],
            'coffee_mosaic' => [
                'label' => __('Coffee mosaic'),
                'description' => __('Warm cafe palette with rounded modules.'),
                'pattern' => 'mosaic',
                'foreground' => '#a16207',
                'background' => '#fffbeb',
                'fallback' => '#451a03',
                'shape' => 'rounded',
                'accent' => '#d97706',
                'surface' => '#fef3c7',
            ],
            'royal_mosaic' => [
                'label' => __('Royal mosaic'),
                'description' => __('Indigo and gold premium mosaic look.'),
                'pattern' => 'mosaic',
                'foreground' => '#4338ca',
                'background' => '#eef2ff',
                'fallback' => '#1e1b4b',
                'shape' => 'diamond',
                'accent' => '#facc15',
                'surface' => '#e0e7ff',
            ],
            'lime_mosaic' => [
                'label' => __('Lime mosaic'),
                'description' => __('Fresh lime dots for food and wellness campaigns.'),
                'pattern' => 'mosaic',
                'foreground' => '#65a30d',
                'background' => '#f7fee7',
                'fallback' => '#365314',
                'shape' => 'circle',
                'accent' => '#22c55e',
                'surface' => '#ecfccb',
            ],
            'ice_mosaic' => [
                'label' => __('Ice mosaic'),
                'description' => __('Soft blue-grey style for clean brands.'),
                'pattern' => 'mosaic',
                'foreground' => '#0369a1',
                'background' => '#f0f9ff',
                'fallback' => '#0f172a',
                'shape' => 'square',
                'accent' => '#7dd3fc',
                'surface' => '#e0f2fe',
            ],
            'carbon_mosaic' => [
                'label' => __('Carbon mosaic'),
                'description' => __('Dark monochrome mosaic for tech products.'),
                'pattern' => 'mosaic',
                'foreground' => '#334155',
                'background' => '#f8fafc',
                'fallback' => '#020617',
                'shape' => 'rounded',
                'accent' => '#94a3b8',
                'surface' => '#e2e8f0',
            ],
        ];
    }

    public static function groups(): array
    {
        $groups = ['basic' => [], 'roundness' => [], 'mosaic' => []];

        foreach (self::all() as $key => $template) {
            $mode = match ($template['pattern']) {
                'mosaic' => 'mosaic',
                'gradient_rounded' => 'roundness',
                default => 'basic',
            };

            $groups[$mode][$key] = array_merge(['key' => $key], $template);
        }

        return $groups;
    }
}
