export { marketManifest } from './manifest.ts';
export {
  strikingDistance,
  lowCtr,
  expectedCtr,
  contentDecay,
  cannibalisation,
  risingQueries,
  type Opportunity,
  type PerformanceRow,
} from './opportunities.ts';
export {
  saveConnection,
  markConnectionFailed,
  upsertKeywords,
  createRankConfig,
  trackKeywords,
  recordRankSnapshots,
  isNotableMove,
  recomputeOpportunities,
  setOpportunityStatus,
  normaliseDomain,
  MarketNotAllowed,
  type KeywordInput,
} from './service.ts';
export {
  syncSearchConsole,
  claimDueConnections,
  type SyncResult,
  type SyncDeps,
} from './sync.ts';
export {
  readAnswer,
  summarise,
  isNotableShift,
  buildProbe,
  prepareBrands,
  hostOf,
  type Brand,
  type ModelAnswer,
  type AnswerReading,
  type BrandReading,
  type VisibilitySnapshot,
} from './visibility.ts';
export {
  runVisibilityProbes,
  claimDuePrompts,
  citedSources,
  urlsIn,
  ASSISTANTS,
  DEFAULT_MODELS,
  type ProbeResult,
  type RunVisibilityResult,
} from './visibility-runner.ts';
export {
  addPrompt,
  setPromptTracked,
  deletePrompt,
  saveCompetitor,
  setSelfBrand,
  deleteCompetitor,
  listPrompts,
  listCompetitors,
  visibilityOverview,
  promptAnswers,
  type PromptRow,
  type CompetitorRow,
  type VisibilityOverview,
} from './visibility-service.ts';
export {
  parseBody,
  scoreContent,
  readingEase,
  syllablesIn,
  wordsOf,
  DENSITY_BAND,
  type Check,
  type ContentScore,
  type Doc,
  type Brief,
  type Parsed,
} from './content-score.ts';
export {
  createDoc,
  saveDoc,
  deleteDoc,
  listDocs,
  getDoc,
  saveBrief,
  briefFromSearchConsole,
  saveDestination,
  slugify,
  DESTINATION_KINDS,
  type DocRow,
  type SaveResult,
} from './content.ts';
export {
  diffTrends,
  worthWriting,
  snapshotKey,
  MIN_INTEREST,
  BASELINE_STALE_DAYS,
  type Reading,
  type Snapshot,
  type Shift,
  type DiffResult,
} from './trends.ts';
export { appearsIn, appearsInflected, mentionsOf, spansOf } from './text.ts';
export {
  runPipeline,
  nextTrigger,
  claimDuePipelines,
  pendingPublishes,
  type PipelineRow,
  type Trigger,
  type RunOutcome,
} from './pipelines.ts';
export {
  runWatch,
  claimDueWatches,
  saveWatch,
  listWatches,
  type TrendSource,
  type WatchRow,
  type WatchOutcome,
} from './trends-runner.ts';
export {
  NETWORKS,
  networkFor,
  countCharacters,
  hashtagsIn,
  hashtagCount,
  validatePost,
  canSchedule,
  splitThread,
  type Network,
  type Problem,
  type PostDraft,
} from './networks.ts';
export {
  nextSlot,
  nextSlots,
  defaultSlots,
  cleanSlots,
  isEmpty,
  DAYS,
  HORIZON_DAYS,
  type Slots,
  type Day,
} from './queue.ts';
export {
  composePost,
  setApproval,
  claimDueTargets,
  recordPublished,
  recordFailure,
  refreshPostStatus,
  listPosts,
  listAccounts,
  saveQueue,
  MAX_ATTEMPTS,
  type ComposeInput,
  type ComposeResult,
  type DueTarget,
  type ShortenLink,
  type SocialDeps,
} from './social.ts';
export {
  AD_PLATFORMS,
  PRESETS,
  FRAMEWORKS,
  TONES,
  OBJECTIVES,
  platformFor,
  presetsFor,
  aspectRatio,
  validateCopy,
  copyIsUsable,
  type AdPlatform,
  type FieldSpec,
  type Preset,
  type CopyProblem,
} from './ad-platforms.ts';
export {
  totalsOf,
  wasting,
  winning,
  stalled,
  creativeFatigue,
  findAll,
  comparisonWindows,
  MIN_CONVERSIONS_FOR_TREND,
  MIN_SPEND_MICROS_FOR_TREND,
  type MetricRow,
  type Totals,
  type Finding,
} from './ad-performance.ts';
export {
  submitCreative,
  pollCreative,
  claimPollable,
  toPromptContext,
  MAX_POLLS,
  POLL_INTERVAL_SECONDS,
  type SubmitInput,
  type SubmitResult,
  type PollOutcome,
  type ProviderStatus,
  type CreativeDeps,
  type BrandSnapshot,
} from './creatives.ts';
export {
  saveBrand,
  listBrands,
  generateCopy,
  parseVariants,
  accountReports,
  recordMetrics,
  listCreatives,
  requireAdAccountHeadroom,
  type CopyVariant,
  type GenerateCopyResult,
  type AccountReport,
} from './ads.ts';
export {
  buildGrid,
  distanceKm,
  summariseGrid,
  gridCost,
  GRID_SIZES,
  type Point,
  type GridPoint,
  type GridSize,
  type GridSummary,
  type GridReading,
} from './geo-grid.ts';
export {
  normaliseName,
  normaliseAddress,
  normalisePhone,
  compareNap,
  actionable,
  type Nap,
  type Difference,
} from './nap.ts';
export {
  listProfiles,
  profileGaps,
  runGrid,
  latestGrids,
  quoteGrid,
  listReviews,
  triage,
  draftReply,
  saveReply,
  saveProfileCategories,
  type LocalProfile,
  type GridRun,
  type ReviewRow,
  type RankPointSource,
} from './local.ts';
