<?php
/*
 * Copyright (c) 2026 AltumCode (https://altumcode.com/)
 *
 * This software is licensed exclusively by AltumCode and is sold only via https://altumcode.com/.
 * Unauthorized distribution, modification, or use of this software without a valid license is not permitted and may be subject to applicable legal actions.
 *
 * 🌍 View all other existing AltumCode projects via https://altumcode.com/
 * 📧 Get in touch for support or general queries via https://altumcode.com/contact
 * 📤 Download the latest version via https://altumcode.com/downloads
 *
 * 🐦 X/Twitter: https://x.com/AltumCode
 * 📘 Facebook: https://facebook.com/altumcode
 * 📸 Instagram: https://instagram.com/altumcode
 */

defined('ALTUMCODE') || die();

return [
    'stockholm' => [
        'name' => 'Stockholm',
        'preview_background_color' => '#f3f4f6',
        'signature' => [
            'background_color' => '#ffffff',
            'border_color' => '#e5e7eb',
            'border_radius' => 8,
            'font_family' => 'arial',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 72,
            'image_border_radius' => 8,
            'socials_width' => 20,
            'socials_padding' => 10,
            'separator_size' => 1,
            'theme_color' => '#111827',
            'full_name_color' => '#111827',
            'text_color' => '#374151',
            'link_color' => '#1d4ed8',
        ],
    ],

    'tokyo' => [
        'name' => 'Tokyo',
        'preview_background_color' => '#eef2ff',
        'signature' => [
            'background_color' => '#f8faff',
            'border_color' => '#c7d2fe',
            'border_radius' => 12,
            'font_family' => 'helvetica',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 76,
            'image_border_radius' => 12,
            'socials_width' => 20,
            'socials_padding' => 9,
            'separator_size' => 2,
            'theme_color' => '#4338ca',
            'full_name_color' => '#1e1b4b',
            'text_color' => '#374151',
            'link_color' => '#3730a3',
        ],
    ],

    'copenhagen' => [
        'name' => 'Copenhagen',
        'preview_background_color' => '#f5f5f4',
        'signature' => [
            'background_color' => '#fafaf9',
            'border_color' => '#d6d3d1',
            'border_radius' => 4,
            'font_family' => 'georgia',
            'font_size' => 14,
            'width' => 440,
            'image_width' => 70,
            'image_border_radius' => 4,
            'socials_width' => 19,
            'socials_padding' => 10,
            'separator_size' => 1,
            'theme_color' => '#57534e',
            'full_name_color' => '#292524',
            'text_color' => '#57534e',
            'link_color' => '#9a3412',
        ],
    ],

    'miami' => [
        'name' => 'Miami',
        'preview_background_color' => '#ecfeff',
        'signature' => [
            'background_color' => '#f0fdff',
            'border_color' => '#a5f3fc',
            'border_radius' => 16,
            'font_family' => 'verdana',
            'font_size' => 13,
            'width' => 460,
            'image_width' => 78,
            'image_border_radius' => 18,
            'socials_width' => 21,
            'socials_padding' => 10,
            'separator_size' => 2,
            'theme_color' => '#0e7490',
            'full_name_color' => '#164e63',
            'text_color' => '#334155',
            'link_color' => '#0e7490',
        ],
    ],

    'lisbon' => [
        'name' => 'Lisbon',
        'preview_background_color' => '#fff7ed',
        'signature' => [
            'background_color' => '#fffaf5',
            'border_color' => '#fed7aa',
            'border_radius' => 10,
            'font_family' => 'georgia',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 74,
            'image_border_radius' => 10,
            'socials_width' => 20,
            'socials_padding' => 9,
            'separator_size' => 2,
            'theme_color' => '#c2410c',
            'full_name_color' => '#7c2d12',
            'text_color' => '#57534e',
            'link_color' => '#c2410c',
        ],
    ],

    'zurich' => [
        'name' => 'Zurich',
        'preview_background_color' => '#eff6ff',
        'signature' => [
            'background_color' => '#f8fbff',
            'border_color' => '#bfdbfe',
            'border_radius' => 6,
            'font_family' => 'arial',
            'font_size' => 13,
            'width' => 440,
            'image_width' => 68,
            'image_border_radius' => 6,
            'socials_width' => 18,
            'socials_padding' => 8,
            'separator_size' => 1,
            'theme_color' => '#2563eb',
            'full_name_color' => '#172554',
            'text_color' => '#334155',
            'link_color' => '#1d4ed8',
        ],
    ],

    'paris' => [
        'name' => 'Paris',
        'preview_background_color' => '#fff1f2',
        'signature' => [
            'background_color' => '#fff7f8',
            'border_color' => '#fecdd3',
            'border_radius' => 14,
            'font_family' => 'georgia',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 76,
            'image_border_radius' => 50,
            'socials_width' => 20,
            'socials_padding' => 10,
            'separator_size' => 1,
            'theme_color' => '#be123c',
            'full_name_color' => '#4c0519',
            'text_color' => '#52525b',
            'link_color' => '#be123c',
        ],
    ],

    'seoul' => [
        'name' => 'Seoul',
        'preview_background_color' => '#f5f3ff',
        'signature' => [
            'background_color' => '#faf8ff',
            'border_color' => '#ddd6fe',
            'border_radius' => 14,
            'font_family' => 'helvetica',
            'font_size' => 14,
            'width' => 460,
            'image_width' => 80,
            'image_border_radius' => 14,
            'socials_width' => 21,
            'socials_padding' => 9,
            'separator_size' => 2,
            'theme_color' => '#7c3aed',
            'full_name_color' => '#2e1065',
            'text_color' => '#3f3f46',
            'link_color' => '#6d28d9',
        ],
    ],

    'amsterdam' => [
        'name' => 'Amsterdam',
        'preview_background_color' => '#f0fdfa',
        'signature' => [
            'background_color' => '#f5fffc',
            'border_color' => '#99f6e4',
            'border_radius' => 12,
            'font_family' => 'verdana',
            'font_size' => 13,
            'width' => 450,
            'image_width' => 72,
            'image_border_radius' => 12,
            'socials_width' => 19,
            'socials_padding' => 8,
            'separator_size' => 2,
            'theme_color' => '#0f766e',
            'full_name_color' => '#134e4a',
            'text_color' => '#374151',
            'link_color' => '#0f766e',
        ],
    ],

    'new_york' => [
        'name' => 'New York',
        'preview_background_color' => '#f8fafc',
        'signature' => [
            'background_color' => '#ffffff',
            'border_color' => '#d1d5db',
            'border_radius' => 0,
            'font_family' => 'helvetica',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 72,
            'image_border_radius' => 0,
            'socials_width' => 20,
            'socials_padding' => 8,
            'separator_size' => 2,
            'theme_color' => '#111827',
            'full_name_color' => '#030712',
            'text_color' => '#374151',
            'link_color' => '#111827',
        ],
    ],

    'singapore' => [
        'name' => 'Singapore',
        'preview_background_color' => '#ecfdf5',
        'signature' => [
            'background_color' => '#f7fffb',
            'border_color' => '#a7f3d0',
            'border_radius' => 16,
            'font_family' => 'arial',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 74,
            'image_border_radius' => 16,
            'socials_width' => 20,
            'socials_padding' => 9,
            'separator_size' => 2,
            'theme_color' => '#047857',
            'full_name_color' => '#064e3b',
            'text_color' => '#374151',
            'link_color' => '#047857',
        ],
    ],

    'dubai' => [
        'name' => 'Dubai',
        'preview_background_color' => '#fffbeb',
        'signature' => [
            'background_color' => '#fffdf5',
            'border_color' => '#fde68a',
            'border_radius' => 6,
            'font_family' => 'georgia',
            'font_size' => 14,
            'width' => 460,
            'image_width' => 82,
            'image_border_radius' => 6,
            'socials_width' => 21,
            'socials_padding' => 10,
            'separator_size' => 2,
            'theme_color' => '#b45309',
            'full_name_color' => '#451a03',
            'text_color' => '#57534e',
            'link_color' => '#b45309',
        ],
    ],

    'kyoto' => [
        'name' => 'Kyoto',
        'preview_background_color' => '#f7fee7',
        'signature' => [
            'background_color' => '#fbfff5',
            'border_color' => '#d9f99d',
            'border_radius' => 12,
            'font_family' => 'georgia',
            'font_size' => 14,
            'width' => 440,
            'image_width' => 70,
            'image_border_radius' => 50,
            'socials_width' => 19,
            'socials_padding' => 9,
            'separator_size' => 1,
            'theme_color' => '#4d7c0f',
            'full_name_color' => '#365314',
            'text_color' => '#4b5563',
            'link_color' => '#3f6212',
        ],
    ],

    'barcelona' => [
        'name' => 'Barcelona',
        'preview_background_color' => '#fffbeb',
        'signature' => [
            'background_color' => '#fffdf5',
            'border_color' => '#fde68a',
            'border_radius' => 12,
            'font_family' => 'verdana',
            'font_size' => 13,
            'width' => 460,
            'image_width' => 78,
            'image_border_radius' => 12,
            'socials_width' => 21,
            'socials_padding' => 10,
            'separator_size' => 3,
            'theme_color' => '#b45309',
            'full_name_color' => '#78350f',
            'text_color' => '#4b5563',
            'link_color' => '#1d4ed8',
        ],
    ],

    'vienna' => [
        'name' => 'Vienna',
        'preview_background_color' => '#faf5ff',
        'signature' => [
            'background_color' => '#fdfaff',
            'border_color' => '#e9d5ff',
            'border_radius' => 16,
            'font_family' => 'georgia',
            'font_size' => 15,
            'width' => 450,
            'image_width' => 78,
            'image_border_radius' => 50,
            'socials_width' => 20,
            'socials_padding' => 10,
            'separator_size' => 1,
            'theme_color' => '#7e22ce',
            'full_name_color' => '#581c87',
            'text_color' => '#52525b',
            'link_color' => '#6b21a8',
        ],
    ],

    'montreal' => [
        'name' => 'Montreal',
        'preview_background_color' => '#fef2f2',
        'signature' => [
            'background_color' => '#fffafa',
            'border_color' => '#fecaca',
            'border_radius' => 10,
            'font_family' => 'arial',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 76,
            'image_border_radius' => 10,
            'socials_width' => 20,
            'socials_padding' => 9,
            'separator_size' => 2,
            'theme_color' => '#b91c1c',
            'full_name_color' => '#7f1d1d',
            'text_color' => '#4b5563',
            'link_color' => '#b91c1c',
        ],
    ],

    'marrakech' => [
        'name' => 'Marrakech',
        'preview_background_color' => '#fff7ed',
        'signature' => [
            'background_color' => '#fff9f5',
            'border_color' => '#fdba74',
            'border_radius' => 8,
            'font_family' => 'georgia',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 80,
            'image_border_radius' => 8,
            'socials_width' => 20,
            'socials_padding' => 10,
            'separator_size' => 3,
            'theme_color' => '#9a3412',
            'full_name_color' => '#7c2d12',
            'text_color' => '#57534e',
            'link_color' => '#9a3412',
        ],
    ],

    'berlin' => [
        'name' => 'Berlin',
        'preview_background_color' => '#f1f5f9',
        'signature' => [
            'background_color' => '#f8fafc',
            'border_color' => '#cbd5e1',
            'border_radius' => 0,
            'font_family' => 'helvetica',
            'font_size' => 13,
            'width' => 440,
            'image_width' => 68,
            'image_border_radius' => 0,
            'socials_width' => 18,
            'socials_padding' => 7,
            'separator_size' => 1,
            'theme_color' => '#475569',
            'full_name_color' => '#0f172a',
            'text_color' => '#475569',
            'link_color' => '#1d4ed8',
        ],
    ],

    'rio_de_janeiro' => [
        'name' => 'Rio de Janeiro',
        'preview_background_color' => '#fdf4ff',
        'signature' => [
            'background_color' => '#fff9ff',
            'border_color' => '#f5d0fe',
            'border_radius' => 18,
            'font_family' => 'verdana',
            'font_size' => 13,
            'width' => 460,
            'image_width' => 82,
            'image_border_radius' => 50,
            'socials_width' => 22,
            'socials_padding' => 10,
            'separator_size' => 3,
            'theme_color' => '#a21caf',
            'full_name_color' => '#701a75',
            'text_color' => '#4b5563',
            'link_color' => '#047857',
        ],
    ],

    'cape_town' => [
        'name' => 'Cape Town',
        'preview_background_color' => '#f0f9ff',
        'signature' => [
            'background_color' => '#f7fcff',
            'border_color' => '#bae6fd',
            'border_radius' => 14,
            'font_family' => 'arial',
            'font_size' => 14,
            'width' => 450,
            'image_width' => 76,
            'image_border_radius' => 14,
            'socials_width' => 20,
            'socials_padding' => 9,
            'separator_size' => 2,
            'theme_color' => '#0e7490',
            'full_name_color' => '#0c4a6e',
            'text_color' => '#334155',
            'link_color' => '#0f766e',
        ],
    ],
];
