<?php

return [
    'heygen' => [
        'base_url'  => 'https://api.heygen.com',
        'languages' => [
            'en'  => 'English',
            'es'  => 'Spanish',
            'fr'  => 'French',
            'de'  => 'German',
            'it'  => 'Italian',
            'pt'  => 'Portuguese',
            'pl'  => 'Polish',
            'zh'  => 'Chinese',
            'ja'  => 'Japanese',
            'ko'  => 'Korean',
            'ar'  => 'Arabic',
            'ru'  => 'Russian',
            'hi'  => 'Hindi',
            'tr'  => 'Turkish',
            'nl'  => 'Dutch',
            'sv'  => 'Swedish',
            'id'  => 'Indonesian',
            'fil' => 'Filipino',
            'ms'  => 'Malay',
            'ro'  => 'Romanian',
            'uk'  => 'Ukrainian',
            'el'  => 'Greek',
            'cs'  => 'Czech',
            'da'  => 'Danish',
            'fi'  => 'Finnish',
            'bg'  => 'Bulgarian',
            'hr'  => 'Croatian',
            'sk'  => 'Slovak',
            'ta'  => 'Tamil',
            'th'  => 'Thai',
            'vi'  => 'Vietnamese',
            'hu'  => 'Hungarian',
            'no'  => 'Norwegian',
            'he'  => 'Hebrew',
            'bn'  => 'Bengali',
            'ur'  => 'Urdu',
            'sw'  => 'Swahili',
            'te'  => 'Telugu',
            'mr'  => 'Marathi',
        ],
    ],
    'elevenlabs' => [
        'base_url'  => 'https://api.elevenlabs.io',
        'languages' => [
            'en'  => 'English',
            'hi'  => 'Hindi',
            'pt'  => 'Portuguese',
            'zh'  => 'Chinese',
            'es'  => 'Spanish',
            'fr'  => 'French',
            'de'  => 'German',
            'ja'  => 'Japanese',
            'ar'  => 'Arabic',
            'ru'  => 'Russian',
            'ko'  => 'Korean',
            'id'  => 'Indonesian',
            'it'  => 'Italian',
            'nl'  => 'Dutch',
            'tr'  => 'Turkish',
            'pl'  => 'Polish',
            'sv'  => 'Swedish',
            'fil' => 'Filipino',
            'ms'  => 'Malay',
            'ro'  => 'Romanian',
            'uk'  => 'Ukrainian',
            'el'  => 'Greek',
            'cs'  => 'Czech',
            'da'  => 'Danish',
            'fi'  => 'Finnish',
            'bg'  => 'Bulgarian',
            'hr'  => 'Croatian',
            'sk'  => 'Slovak',
            'ta'  => 'Tamil',
        ],
    ],
];
