<?php
/*
 * Copyright (c) 2026 AltumCode (https://altumcode.com/)
 *
 * This software is proprietary software owned and licensed by AltumCode.
 * A valid license is required to use, modify, or distribute this software.
 * Unauthorized use, reproduction, modification, or distribution is prohibited.
 *
 * 🌍 Explore all AltumCode projects: https://altumcode.com/
 * 📧 Support & general inquiries: https://altumcode.com/contact
 * 📤 Download the latest version: https://altumcode.com/downloads
 *
 * 🐦 X/Twitter: https://x.com/AltumCode
 */

defined('ALTUMCODE') || die();

/* Keep a smooth visual order in the theme picker */
return [
    'stockholm' => [
        'name' => 'Stockholm',
        'preview_background_color' => '#f3f4f6',
        'preview_image' => 'stockholm.svg',
        'qr_code' => [
            'style' => 'square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#111827',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#111827',
            'foreground_gradient_two' => '#374151',
            'background_color' => '#ffffff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#111827',
            'eyes_outer_color' => '#111827',
            'frame' => 'straight_simple_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#111827',
            'frame_text_color' => '#111827',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'new_york' => [
        'name' => 'New York',
        'preview_background_color' => '#f8fafc',
        'preview_image' => 'new_york.svg',
        'qr_code' => [
            'style' => 'spaced_square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#0f172a',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#0f172a',
            'foreground_gradient_two' => '#334155',
            'background_color' => '#ffffff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#0f172a',
            'eyes_outer_color' => '#0f172a',
            'frame' => 'straight_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#0f172a',
            'frame_text_color' => '#ffffff',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'tokyo' => [
        'name' => 'Tokyo',
        'preview_background_color' => '#eef2ff',
        'preview_image' => 'tokyo.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#312e81',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#312e81',
            'foreground_gradient_two' => '#6d28d9',
            'background_color' => '#fff7ff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#6d28d9',
            'eyes_outer_color' => '#312e81',
            'frame' => 'round_card_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#312e81',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'miami' => [
        'name' => 'Miami',
        'preview_background_color' => '#ffe4e6',
        'preview_image' => 'miami.svg',
        'qr_code' => [
            'style' => 'dot',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#9f1239',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#9f1239',
            'foreground_gradient_two' => '#9a3412',
            'background_color' => '#fff7ed',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#9a3412',
            'eyes_outer_color' => '#9f1239',
            'frame' => 'circle_simple_bottom_text',
            'frame_text_font' => 'verdana',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#9f1239',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'amsterdam' => [
        'name' => 'Amsterdam',
        'preview_background_color' => '#f0fdfa',
        'preview_image' => 'amsterdam.svg',
        'qr_code' => [
            'style' => 'round',
            'inner_eye_style' => 'leaf',
            'outer_eye_style' => 'leaf',
            'foreground_type' => 'gradient',
            'foreground_color' => '#064e3b',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#064e3b',
            'foreground_gradient_two' => '#0f766e',
            'background_color' => '#f5fffc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0f766e',
            'eyes_outer_color' => '#064e3b',
            'frame' => 'round_simple_bottom_text',
            'frame_text_font' => 'verdana',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#064e3b',
            'frame_text_color' => '#064e3b',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'singapore' => [
        'name' => 'Singapore',
        'preview_background_color' => '#0f172a',
        'preview_image' => 'singapore.svg',
        'qr_code' => [
            'style' => 'hexagon',
            'inner_eye_style' => 'hexagon',
            'outer_eye_style' => 'hexagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#67e8f9',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#67e8f9',
            'foreground_gradient_two' => '#5eead4',
            'background_color' => '#0f172a',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#5eead4',
            'eyes_outer_color' => '#67e8f9',
            'frame' => 'round_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#0f766e',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'kyoto' => [
        'name' => 'Kyoto',
        'preview_background_color' => '#f7fee7',
        'preview_image' => 'kyoto.svg',
        'qr_code' => [
            'style' => 'round',
            'inner_eye_style' => 'leaf',
            'outer_eye_style' => 'leaf',
            'foreground_type' => 'color',
            'foreground_color' => '#365314',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#365314',
            'foreground_gradient_two' => '#65a30d',
            'background_color' => '#fbfff5',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#4d7c0f',
            'eyes_outer_color' => '#365314',
            'frame' => 'smooth_ribbon_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#4d7c0f',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'athens' => [
        'name' => 'Athens',
        'preview_background_color' => '#e0f2fe',
        'preview_image' => 'athens.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#075985',
            'foreground_gradient_style' => 'radial',
            'foreground_gradient_one' => '#075985',
            'foreground_gradient_two' => '#0e7490',
            'background_color' => '#f0f9ff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0e7490',
            'eyes_outer_color' => '#075985',
            'frame' => 'ribbon_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#075985',
            'frame_text_color' => '#ffffff',
            'margin' => 2,
            'ecc' => 'Q',
        ],
    ],

    'barcelona' => [
        'name' => 'Barcelona',
        'preview_background_color' => '#fff1f2',
        'preview_image' => 'barcelona.svg',
        'qr_code' => [
            'style' => 'diamond',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#6d28d9',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#6d28d9',
            'foreground_gradient_two' => '#be185d',
            'background_color' => '#fdf4ff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#be185d',
            'eyes_outer_color' => '#6d28d9',
            'frame' => 'tooltip_bottom_text',
            'frame_text_font' => 'verdana',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#6d28d9',
            'frame_text_color' => '#ffffff',
            'margin' => 2,
            'ecc' => 'Q',
        ],
    ],

    'lisbon' => [
        'name' => 'Lisbon',
        'preview_background_color' => '#fff7ed',
        'preview_image' => 'lisbon.svg',
        'qr_code' => [
            'style' => 'teardrop',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#9a3412',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#9a3412',
            'foreground_gradient_two' => '#b45309',
            'background_color' => '#fffaf5',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#b45309',
            'eyes_outer_color' => '#9a3412',
            'frame' => 'round_semi_bordered_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#9a3412',
            'frame_text_color' => '#7c2d12',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'marrakech' => [
        'name' => 'Marrakech',
        'preview_background_color' => '#fff7ed',
        'preview_image' => 'marrakech.svg',
        'qr_code' => [
            'style' => 'corner_cut',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#7c2d12',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#7c2d12',
            'foreground_gradient_two' => '#9f1239',
            'background_color' => '#fff9f5',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#9f1239',
            'eyes_outer_color' => '#7c2d12',
            'frame' => 'straight_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#7f1d1d',
            'frame_text_color' => '#ffffff',
            'margin' => 2,
            'ecc' => 'Q',
        ],
    ],

    'dubai' => [
        'name' => 'Dubai',
        'preview_background_color' => '#fffbeb',
        'preview_image' => 'dubai.svg',
        'qr_code' => [
            'style' => 'octagon',
            'inner_eye_style' => 'octagon',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#fbbf24',
            'foreground_gradient_style' => 'radial',
            'foreground_gradient_one' => '#fbbf24',
            'foreground_gradient_two' => '#fde68a',
            'background_color' => '#111827',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#fde68a',
            'eyes_outer_color' => '#fbbf24',
            'frame' => 'straight_top_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#b45309',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'montreal' => [
        'name' => 'Montreal',
        'preview_background_color' => '#fef2f2',
        'preview_image' => 'montreal.svg',
        'qr_code' => [
            'style' => 'spaced_square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#b91c1c',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#b91c1c',
            'foreground_gradient_two' => '#dc2626',
            'background_color' => '#fffafa',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#b91c1c',
            'eyes_outer_color' => '#b91c1c',
            'frame' => 'straight_semi_bordered_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#7f1d1d',
            'frame_text_color' => '#7f1d1d',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'paris' => [
        'name' => 'Paris',
        'preview_background_color' => '#fff1f2',
        'preview_image' => 'paris.svg',
        'qr_code' => [
            'style' => 'heart',
            'inner_eye_style' => 'heart',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#be123c',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#be123c',
            'foreground_gradient_two' => '#7e22ce',
            'background_color' => '#fff7fb',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#7e22ce',
            'eyes_outer_color' => '#be123c',
            'frame' => 'round_top_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#4c0519',
            'frame_text_color' => '#fff1f2',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'vienna' => [
        'name' => 'Vienna',
        'preview_background_color' => '#faf5ff',
        'preview_image' => 'vienna.svg',
        'qr_code' => [
            'style' => 'dot',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#581c87',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#581c87',
            'foreground_gradient_two' => '#7e22ce',
            'background_color' => '#fdfaff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#7e22ce',
            'eyes_outer_color' => '#581c87',
            'frame' => 'round_top_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#581c87',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'seoul' => [
        'name' => 'Seoul',
        'preview_background_color' => '#f5f3ff',
        'preview_image' => 'seoul.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#6d28d9',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#6d28d9',
            'foreground_gradient_two' => '#be185d',
            'background_color' => '#faf8ff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#be185d',
            'eyes_outer_color' => '#6d28d9',
            'frame' => 'smooth_ribbon_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#4c1d95',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'monaco' => [
        'name' => 'Monaco',
        'preview_background_color' => '#f4f4f5',
        'preview_image' => 'monaco.svg',
        'qr_code' => [
            'style' => 'square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#18181b',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#18181b',
            'foreground_gradient_two' => '#7f1d1d',
            'background_color' => '#ffffff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#9f1239',
            'eyes_outer_color' => '#18181b',
            'frame' => 'straight_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#7f1d1d',
            'frame_text_color' => '#ffffff',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'oslo' => [
        'name' => 'Oslo',
        'preview_background_color' => '#eff6ff',
        'preview_image' => 'oslo.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'color',
            'foreground_color' => '#1e3a8a',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#1e3a8a',
            'foreground_gradient_two' => '#3b82f6',
            'background_color' => '#f8fbff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#1d4ed8',
            'eyes_outer_color' => '#1e3a8a',
            'frame' => 'round_simple_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e3a8a',
            'frame_text_color' => '#1e3a8a',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'reykjavik' => [
        'name' => 'Reykjavik',
        'preview_background_color' => '#cffafe',
        'preview_image' => 'reykjavik.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#155e75',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#155e75',
            'foreground_gradient_two' => '#0f766e',
            'background_color' => '#ecfeff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0f766e',
            'eyes_outer_color' => '#155e75',
            'frame' => 'round_top_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#155e75',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'cairo' => [
        'name' => 'Cairo',
        'preview_background_color' => '#fef3c7',
        'preview_image' => 'cairo.svg',
        'qr_code' => [
            'style' => 'corner_cut',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#78350f',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#78350f',
            'foreground_gradient_two' => '#92400e',
            'background_color' => '#fffbeb',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#92400e',
            'eyes_outer_color' => '#78350f',
            'frame' => 'ribbon_top_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#78350f',
            'frame_text_color' => '#fef3c7',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'nairobi' => [
        'name' => 'Nairobi',
        'preview_background_color' => '#f7fee7',
        'preview_image' => 'nairobi.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#166534',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#166534',
            'foreground_gradient_two' => '#15803d',
            'background_color' => '#f7fee7',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#15803d',
            'eyes_outer_color' => '#166534',
            'frame' => 'straight_semi_bordered_bottom_text',
            'frame_text_font' => 'verdana',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#14532d',
            'frame_text_color' => '#14532d',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'rio' => [
        'name' => 'Rio',
        'preview_background_color' => '#ecfccb',
        'preview_image' => 'rio.svg',
        'qr_code' => [
            'style' => 'dot',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#15803d',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#15803d',
            'foreground_gradient_two' => '#0f766e',
            'background_color' => '#f0fdf4',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0f766e',
            'eyes_outer_color' => '#15803d',
            'frame' => 'circle_simple_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#166534',
            'frame_text_color' => '#dcfce7',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'cape_town' => [
        'name' => 'Cape Town',
        'preview_background_color' => '#ccfbf1',
        'preview_image' => 'cape_town.svg',
        'qr_code' => [
            'style' => 'corner_cut',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#0f766e',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#0f766e',
            'foreground_gradient_two' => '#0369a1',
            'background_color' => '#f0fdfa',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0369a1',
            'eyes_outer_color' => '#0f766e',
            'frame' => 'tooltip_top_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#0f766e',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'sydney' => [
        'name' => 'Sydney',
        'preview_background_color' => '#eff6ff',
        'preview_image' => 'sydney.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#1d4ed8',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#1d4ed8',
            'foreground_gradient_two' => '#0369a1',
            'background_color' => '#f8fbff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0369a1',
            'eyes_outer_color' => '#1d4ed8',
            'frame' => 'round_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e3a8a',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'berlin' => [
        'name' => 'Berlin',
        'preview_background_color' => '#f4f4f5',
        'preview_image' => 'berlin.svg',
        'qr_code' => [
            'style' => 'spaced_square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#1f2937',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#1f2937',
            'foreground_gradient_two' => '#475569',
            'background_color' => '#f9fafb',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#1f2937',
            'eyes_outer_color' => '#1f2937',
            'frame' => 'straight_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#111827',
            'frame_text_color' => '#d1fae5',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'toronto' => [
        'name' => 'Toronto',
        'preview_background_color' => '#fee2e2',
        'preview_image' => 'toronto.svg',
        'qr_code' => [
            'style' => 'corner_cut',
            'inner_eye_style' => 'shield',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'color',
            'foreground_color' => '#991b1b',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#991b1b',
            'foreground_gradient_two' => '#ef4444',
            'background_color' => '#fff5f5',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#991b1b',
            'eyes_outer_color' => '#991b1b',
            'frame' => 'ribbon_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#991b1b',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'prague' => [
        'name' => 'Prague',
        'preview_background_color' => '#fce7f3',
        'preview_image' => 'prague.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#881337',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#881337',
            'foreground_gradient_two' => '#9f1239',
            'background_color' => '#fff7fb',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#9f1239',
            'eyes_outer_color' => '#881337',
            'frame' => 'round_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#881337',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'zurich' => [
        'name' => 'Zurich',
        'preview_background_color' => '#e0f2fe',
        'preview_image' => 'zurich.svg',
        'qr_code' => [
            'style' => 'square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'color',
            'foreground_color' => '#0369a1',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#0369a1',
            'foreground_gradient_two' => '#0284c7',
            'background_color' => '#ffffff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0369a1',
            'eyes_outer_color' => '#0369a1',
            'frame' => 'round_card_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#dbeafe',
            'frame_text_color' => '#1e3a8a',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'havana' => [
        'name' => 'Havana',
        'preview_background_color' => '#ffedd5',
        'preview_image' => 'havana.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#9a3412',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#9a3412',
            'foreground_gradient_two' => '#be123c',
            'background_color' => '#fff7ed',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#be123c',
            'eyes_outer_color' => '#9a3412',
            'frame' => 'tooltip_bottom_text',
            'frame_text_font' => 'verdana',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#9a3412',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'bali' => [
        'name' => 'Bali',
        'preview_background_color' => '#d1fae5',
        'preview_image' => 'bali.svg',
        'qr_code' => [
            'style' => 'round',
            'inner_eye_style' => 'leaf',
            'outer_eye_style' => 'leaf',
            'foreground_type' => 'gradient',
            'foreground_color' => '#047857',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#047857',
            'foreground_gradient_two' => '#0f766e',
            'background_color' => '#f0fdfa',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0f766e',
            'eyes_outer_color' => '#047857',
            'frame' => 'round_semi_bordered_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#047857',
            'frame_text_color' => '#047857',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'lagos' => [
        'name' => 'Lagos',
        'preview_background_color' => '#fef3c7',
        'preview_image' => 'lagos.svg',
        'qr_code' => [
            'style' => 'corner_cut',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#92400e',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#92400e',
            'foreground_gradient_two' => '#b45309',
            'background_color' => '#fffbeb',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#b45309',
            'eyes_outer_color' => '#92400e',
            'frame' => 'straight_top_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#78350f',
            'frame_text_color' => '#fef3c7',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'helsinki' => [
        'name' => 'Helsinki',
        'preview_background_color' => '#e0f2fe',
        'preview_image' => 'helsinki.svg',
        'qr_code' => [
            'style' => 'square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#1e3a8a',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#1e3a8a',
            'foreground_gradient_two' => '#1d4ed8',
            'background_color' => '#ffffff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#1e3a8a',
            'eyes_outer_color' => '#1e3a8a',
            'frame' => 'straight_simple_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e3a8a',
            'frame_text_color' => '#1e3a8a',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'london' => [
        'name' => 'London',
        'preview_background_color' => '#f4f4f5',
        'preview_image' => 'london.svg',
        'qr_code' => [
            'style' => 'spaced_square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'color',
            'foreground_color' => '#18181b',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#18181b',
            'foreground_gradient_two' => '#7f1d1d',
            'background_color' => '#fafafa',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#7f1d1d',
            'eyes_outer_color' => '#18181b',
            'frame' => 'straight_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#18181b',
            'frame_text_color' => '#ffffff',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'san_francisco' => [
        'name' => 'San Francisco',
        'preview_background_color' => '#e0f2fe',
        'preview_image' => 'san_francisco.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#1e40af',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#1e40af',
            'foreground_gradient_two' => '#0f766e',
            'background_color' => '#f8fafc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0f766e',
            'eyes_outer_color' => '#1e40af',
            'frame' => 'round_card_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e40af',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'copenhagen' => [
        'name' => 'Copenhagen',
        'preview_background_color' => '#eff6ff',
        'preview_image' => 'copenhagen.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'color',
            'foreground_color' => '#1e3a8a',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#1e3a8a',
            'foreground_gradient_two' => '#1d4ed8',
            'background_color' => '#f8fbff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 0,
            'eyes_inner_color' => '#1e3a8a',
            'eyes_outer_color' => '#1e3a8a',
            'frame' => 'round_simple_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e3a8a',
            'frame_text_color' => '#1e3a8a',
            'margin' => 2,
            'ecc' => 'M',
        ],
    ],

    'venice' => [
        'name' => 'Venice',
        'preview_background_color' => '#ccfbf1',
        'preview_image' => 'venice.svg',
        'qr_code' => [
            'style' => 'teardrop',
            'inner_eye_style' => 'leaf',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#115e59',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#115e59',
            'foreground_gradient_two' => '#0369a1',
            'background_color' => '#f0fdfa',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0369a1',
            'eyes_outer_color' => '#115e59',
            'frame' => 'round_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#115e59',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'istanbul' => [
        'name' => 'Istanbul',
        'preview_background_color' => '#e0f2fe',
        'preview_image' => 'istanbul.svg',
        'qr_code' => [
            'style' => 'diamond',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#1e3a8a',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#1e3a8a',
            'foreground_gradient_two' => '#075985',
            'background_color' => '#f8fafc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#075985',
            'eyes_outer_color' => '#1e3a8a',
            'frame' => 'tooltip_top_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e3a8a',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'mexico_city' => [
        'name' => 'Mexico City',
        'preview_background_color' => '#dcfce7',
        'preview_image' => 'mexico_city.svg',
        'qr_code' => [
            'style' => 'corner_cut',
            'inner_eye_style' => 'shield',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#14532d',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#14532d',
            'foreground_gradient_two' => '#047857',
            'background_color' => '#f7fee7',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#047857',
            'eyes_outer_color' => '#14532d',
            'frame' => 'ribbon_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#14532d',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'buenos_aires' => [
        'name' => 'Buenos Aires',
        'preview_background_color' => '#e0f2fe',
        'preview_image' => 'buenos_aires.svg',
        'qr_code' => [
            'style' => 'dot',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#1d4ed8',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#1d4ed8',
            'foreground_gradient_two' => '#0369a1',
            'background_color' => '#f0f9ff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0369a1',
            'eyes_outer_color' => '#1d4ed8',
            'frame' => 'circle_simple_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e40af',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'hong_kong' => [
        'name' => 'Hong Kong',
        'preview_background_color' => '#fee2e2',
        'preview_image' => 'hong_kong.svg',
        'qr_code' => [
            'style' => 'square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'gradient',
            'foreground_color' => '#991b1b',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#991b1b',
            'foreground_gradient_two' => '#be123c',
            'background_color' => '#fff7ed',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#be123c',
            'eyes_outer_color' => '#991b1b',
            'frame' => 'straight_top_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#991b1b',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'bangkok' => [
        'name' => 'Bangkok',
        'preview_background_color' => '#f3e8ff',
        'preview_image' => 'bangkok.svg',
        'qr_code' => [
            'style' => 'diamond',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#581c87',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#581c87',
            'foreground_gradient_two' => '#7e22ce',
            'background_color' => '#fdf4ff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#7e22ce',
            'eyes_outer_color' => '#581c87',
            'frame' => 'round_card_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#581c87',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'melbourne' => [
        'name' => 'Melbourne',
        'preview_background_color' => '#e2e8f0',
        'preview_image' => 'melbourne.svg',
        'qr_code' => [
            'style' => 'spaced_square',
            'inner_eye_style' => 'square',
            'outer_eye_style' => 'square',
            'foreground_type' => 'gradient',
            'foreground_color' => '#1f2937',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#1f2937',
            'foreground_gradient_two' => '#1d4ed8',
            'background_color' => '#f8fafc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#1d4ed8',
            'eyes_outer_color' => '#1f2937',
            'frame' => 'tooltip_bottom_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#111827',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'brussels' => [
        'name' => 'Brussels',
        'preview_background_color' => '#dbeafe',
        'preview_image' => 'brussels.svg',
        'qr_code' => [
            'style' => 'diamond',
            'inner_eye_style' => 'diamond',
            'outer_eye_style' => 'octagon',
            'foreground_type' => 'gradient',
            'foreground_color' => '#1e3a8a',
            'foreground_gradient_style' => 'diagonal',
            'foreground_gradient_one' => '#1e3a8a',
            'foreground_gradient_two' => '#1d4ed8',
            'background_color' => '#f8fafc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#1d4ed8',
            'eyes_outer_color' => '#1e3a8a',
            'frame' => 'ribbon_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#1e3a8a',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'edinburgh' => [
        'name' => 'Edinburgh',
        'preview_background_color' => '#dcfce7',
        'preview_image' => 'edinburgh.svg',
        'qr_code' => [
            'style' => 'round',
            'inner_eye_style' => 'leaf',
            'outer_eye_style' => 'leaf',
            'foreground_type' => 'gradient',
            'foreground_color' => '#14532d',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#14532d',
            'foreground_gradient_two' => '#166534',
            'background_color' => '#f8fafc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#166534',
            'eyes_outer_color' => '#14532d',
            'frame' => 'round_semi_bordered_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#14532d',
            'frame_text_color' => '#14532d',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],

    'salvador' => [
        'name' => 'Salvador',
        'preview_background_color' => '#cffafe',
        'preview_image' => 'salvador.svg',
        'qr_code' => [
            'style' => 'dot',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#0f766e',
            'foreground_gradient_style' => 'inverse_diagonal',
            'foreground_gradient_one' => '#0f766e',
            'foreground_gradient_two' => '#1d4ed8',
            'background_color' => '#ecfeff',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#1d4ed8',
            'eyes_outer_color' => '#0f766e',
            'frame' => 'smooth_ribbon_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#155e75',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'taipei' => [
        'name' => 'Taipei',
        'preview_background_color' => '#ede9fe',
        'preview_image' => 'taipei.svg',
        'qr_code' => [
            'style' => 'rounded',
            'inner_eye_style' => 'rounded',
            'outer_eye_style' => 'rounded',
            'foreground_type' => 'gradient',
            'foreground_color' => '#4338ca',
            'foreground_gradient_style' => 'vertical',
            'foreground_gradient_one' => '#4338ca',
            'foreground_gradient_two' => '#6d28d9',
            'background_color' => '#f8fafc',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#6d28d9',
            'eyes_outer_color' => '#4338ca',
            'frame' => 'tooltip_top_text',
            'frame_text_font' => 'helvetica',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#312e81',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'delhi' => [
        'name' => 'Delhi',
        'preview_background_color' => '#ffedd5',
        'preview_image' => 'delhi.svg',
        'qr_code' => [
            'style' => 'teardrop',
            'inner_eye_style' => 'dot',
            'outer_eye_style' => 'circle',
            'foreground_type' => 'gradient',
            'foreground_color' => '#9a3412',
            'foreground_gradient_style' => 'radial',
            'foreground_gradient_one' => '#9a3412',
            'foreground_gradient_two' => '#b91c1c',
            'background_color' => '#fff7ed',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#b91c1c',
            'eyes_outer_color' => '#9a3412',
            'frame' => 'round_bottom_text',
            'frame_text_font' => 'georgia',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#9a3412',
            'frame_text_color' => '#ffffff',
            'margin' => 1,
            'ecc' => 'Q',
        ],
    ],

    'medellin' => [
        'name' => 'Medellin',
        'preview_background_color' => '#dcfce7',
        'preview_image' => 'medellin.svg',
        'qr_code' => [
            'style' => 'round',
            'inner_eye_style' => 'leaf',
            'outer_eye_style' => 'leaf',
            'foreground_type' => 'gradient',
            'foreground_color' => '#166534',
            'foreground_gradient_style' => 'horizontal',
            'foreground_gradient_one' => '#166534',
            'foreground_gradient_two' => '#0f766e',
            'background_color' => '#f0fdf4',
            'background_color_transparency' => 0,
            'custom_eyes_color' => 1,
            'eyes_inner_color' => '#0f766e',
            'eyes_outer_color' => '#166534',
            'frame' => 'round_simple_bottom_text',
            'frame_text_font' => 'arial',
            'frame_text_size' => 0,
            'frame_custom_colors' => 1,
            'frame_color' => '#166534',
            'frame_text_color' => '#166534',
            'margin' => 1,
            'ecc' => 'M',
        ],
    ],
];
