<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class CreateSettingsTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->string('name', 128)->primary();
            $table->text('value')->nullable();
        });

        DB::table('settings')->insert(
            [
                ['name' => 'announcement_guest', 'value' => ''],
                ['name' => 'announcement_guest_id', 'value' => 'cwUOUj7dQZZzJstZ'],
                ['name' => 'announcement_guest_type', 'value' => 'info'],
                ['name' => 'announcement_user', 'value' => ''],
                ['name' => 'announcement_user_id', 'value' => 'p0VIvAg0FU26HN2v'],
                ['name' => 'announcement_user_type', 'value' => 'info'],
                ['name' => 'auth_remember_me_duration', 'value' => 129600],
                ['name' => 'auth_google', 'value' => ''],
                ['name' => 'auth_google_client_id', 'value' => ''],
                ['name' => 'auth_google_client_secret', 'value' => ''],
                ['name' => 'auth_microsoft', 'value' => ''],
                ['name' => 'auth_microsoft_client_id', 'value' => ''],
                ['name' => 'auth_microsoft_client_secret', 'value' => ''],
                ['name' => 'auth_apple', 'value' => ''],
                ['name' => 'auth_apple_client_id', 'value' => ''],
                ['name' => 'auth_apple_client_secret', 'value' => ''],
                ['name' => 'bad_words', 'value' => ''],
                ['name' => 'bank', 'value' => '0'],
                ['name' => 'bank_account_number', 'value' => ''],
                ['name' => 'bank_account_owner', 'value' => ''],
                ['name' => 'bank_bic_swift', 'value' => ''],
                ['name' => 'bank_iban', 'value' => ''],
                ['name' => 'bank_name', 'value' => ''],
                ['name' => 'bank_routing_number', 'value' => ''],
                ['name' => 'billing_address', 'value' => ''],
                ['name' => 'billing_city', 'value' => ''],
                ['name' => 'billing_country', 'value' => ''],
                ['name' => 'billing_invoice_prefix', 'value' => ''],
                ['name' => 'billing_phone', 'value' => ''],
                ['name' => 'billing_postal_code', 'value' => ''],
                ['name' => 'billing_state', 'value' => ''],
                ['name' => 'billing_vat_number', 'value' => ''],
                ['name' => 'billing_vendor', 'value' => ''],
                ['name' => 'captcha_driver', 'value' => ''],
                ['name' => 'captcha_secret_key', 'value' => ''],
                ['name' => 'captcha_site_key', 'value' => ''],
                ['name' => 'coinbase', 'value' => '0'],
                ['name' => 'coinbase_key', 'value' => ''],
                ['name' => 'coinbase_wh_secret', 'value' => ''],
                ['name' => 'contact_address', 'value' => ''],
                ['name' => 'contact_email', 'value' => ''],
                ['name' => 'contact_email_public', 'value' => ''],
                ['name' => 'contact_form', 'value' => '0'],
                ['name' => 'contact_phone', 'value' => ''],
                ['name' => 'cronjob_executed_at', 'value' => NULL],
                ['name' => 'cronjob_key', 'value' => Str::random(32)],
                ['name' => 'cryptocom', 'value' => NULL],
                ['name' => 'cryptocom_key', 'value' => NULL],
                ['name' => 'cryptocom_secret', 'value' => NULL],
                ['name' => 'cryptocom_wh_secret', 'value' => NULL],
                ['name' => 'custom_css', 'value' => '@import url("https://rsms.me/inter/inter.css");'],
                ['name' => 'custom_js', 'value' => ''],
                ['name' => 'demo_url', 'value' => ''],
                ['name' => 'domain_protocol', 'value' => 'http'],
                ['name' => 'email_address', 'value' => ''],
                ['name' => 'email_driver', 'value' => 'log'],
                ['name' => 'email_encryption', 'value' => 'tls'],
                ['name' => 'email_host', 'value' => ''],
                ['name' => 'email_password', 'value' => ''],
                ['name' => 'email_port', 'value' => ''],
                ['name' => 'email_username', 'value' => ''],
                ['name' => 'favicon', 'value' => 'favicon.png'],
                ['name' => 'force_https', 'value' => '1'],
                ['name' => 'homepage_checks_country_code', 'value' => 'US'],
                ['name' => 'index', 'value' => ''],
                ['name' => 'image_driver', 'value' => 'gd'],
                ['name' => 'legal_cookie_url', 'value' => ''],
                ['name' => 'legal_privacy_url', 'value' => ''],
                ['name' => 'legal_terms_url', 'value' => ''],
                ['name' => 'license_key', 'value' => NULL],
                ['name' => 'license_type', 'value' => NULL],
                ['name' => 'locale', 'value' => 'en'],
                ['name' => 'login_tfa', 'value' => '0'],
                ['name' => 'logo', 'value' => 'logo.svg'],
                ['name' => 'logo_dark', 'value' => 'logo-dark.svg'],
                ['name' => 'monitors_inactive_days', 'value' => 10],
                ['name' => 'paginate', 'value' => '10'],
                ['name' => 'paypal', 'value' => '0'],
                ['name' => 'paypal_client_id', 'value' => ''],
                ['name' => 'paypal_mode', 'value' => 'sandbox'],
                ['name' => 'paypal_secret', 'value' => ''],
                ['name' => 'paypal_webhook_id', 'value' => ''],
                ['name' => 'paystack', 'value' => NULL],
                ['name' => 'paystack_key', 'value' => NULL],
                ['name' => 'paystack_secret', 'value' => NULL],
                ['name' => 'razorpay', 'value' => NULL],
                ['name' => 'razorpay_key', 'value' => NULL],
                ['name' => 'razorpay_secret', 'value' => NULL],
                ['name' => 'razorpay_wh_secret', 'value' => NULL],
                ['name' => 'registration', 'value' => '1'],
                ['name' => 'registration_tfa', 'value' => '0'],
                ['name' => 'registration_verification', 'value' => '1'],
                ['name' => 'request_simultaneous_requests', 'value' => 100],
                ['name' => 'request_proxy', 'value' => null],
                ['name' => 'request_timeout', 'value' => 10],
                ['name' => 'request_user_agent', 'value' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'],
                ['name' => 'request_http_version', 'value' => '1.1'],
                ['name' => 'social_discord', 'value' => ''],
                ['name' => 'social_facebook', 'value' => ''],
                ['name' => 'social_github', 'value' => ''],
                ['name' => 'social_instagram', 'value' => ''],
                ['name' => 'social_linkedin', 'value' => ''],
                ['name' => 'social_pinterest', 'value' => ''],
                ['name' => 'social_reddit', 'value' => ''],
                ['name' => 'social_threads', 'value' => ''],
                ['name' => 'social_tiktok', 'value' => ''],
                ['name' => 'social_tumblr', 'value' => ''],
                ['name' => 'social_x', 'value' => ''],
                ['name' => 'social_youtube', 'value' => ''],
                ['name' => 'status_page_logo_filesize', 'value' => 2],
                ['name' => 'status_page_logo_format', 'value' => 'jpeg,png,gif,bmp,svg'],
                ['name' => 'status_page_favicon_filesize', 'value' => 2],
                ['name' => 'status_page_favicon_format', 'value' => 'ico,png,gif,svg'],
                ['name' => 'status_page_refresh_interval', 'value' => 60],
                ['name' => 'status_pages_max_monitors', 'value' => 200],
                ['name' => 'storage_driver', 'value' => 'public'],
                ['name' => 'storage_key', 'value' => ''],
                ['name' => 'storage_secret', 'value' => ''],
                ['name' => 'storage_region', 'value' => ''],
                ['name' => 'storage_bucket', 'value' => ''],
                ['name' => 'storage_url', 'value' => ''],
                ['name' => 'storage_endpoint', 'value' => ''],
                ['name' => 'storage_use_path_style_endpoint', 'value' => ''],
                ['name' => 'storage_throw', 'value' => ''],
                ['name' => 'monitor_refresh_interval', 'value' => 10],
                ['name' => 'monitors_pause_plan_limits_grace_days', 'value' => 3],
                ['name' => 'monitors_pause_inactive_users_grace_days', 'value' => 0],
                ['name' => 'status_days', 'value' => 30],
                ['name' => 'stripe', 'value' => '0'],
                ['name' => 'stripe_key', 'value' => ''],
                ['name' => 'stripe_secret', 'value' => ''],
                ['name' => 'stripe_wh_secret', 'value' => ''],
                ['name' => 'tagline', 'value' => 'Reliable uptime monitoring'],
                ['name' => 'theme', 'value' => '0'],
                ['name' => 'timezone', 'value' => 'UTC'],
                ['name' => 'title', 'value' => 'phpUptime'],
                ['name' => 'twilio', 'value' => ''],
                ['name' => 'twilio_sid', 'value' => ''],
                ['name' => 'twilio_token', 'value' => ''],
                ['name' => 'twilio_phone_number', 'value' => ''],
                ['name' => 'twilio_sms_url', 'value' => 0],
                ['name' => 'user_avatar_filesize', 'value' => 2],
                ['name' => 'user_avatar_format', 'value' => 'jpeg,png,gif,bmp'],
                ['name' => 'user_avatar_size', 'value' => 256],
                ['name' => 'webhook_user_deleted', 'value' => NULL],
                ['name' => 'webhook_user_created', 'value' => NULL],
                ['name' => 'webhook_user_updated', 'value' => NULL],
                ['name' => 'webhook_status_page_deleted', 'value' => NULL],
                ['name' => 'webhook_status_page_created', 'value' => NULL],
                ['name' => 'webhook_status_page_updated', 'value' => NULL]
            ]
        );
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('settings');
    }
}
