<?php
/*
 * Copyright (c) 2026 AltumCode (https://altumcode.com/)
 *
 * This software is licensed exclusively by AltumCode and is sold only via https://altumcode.com/.
 * Unauthorized distribution, modification, or use of this software without a valid license is not permitted and may be subject to applicable legal actions.
 *
 * 🌍 View all other existing AltumCode projects via https://altumcode.com/
 * 📧 Get in touch for support or general queries via https://altumcode.com/contact
 * 📤 Download the latest version via https://altumcode.com/downloads
 *
 * 🐦 X/Twitter: https://x.com/AltumCode
 * 📘 Facebook: https://facebook.com/altumcode
 * 📸 Instagram: https://instagram.com/altumcode
 */

defined('ALTUMCODE') || die();

/* Keep a smooth visual order in the theme picker */
$themes = [
    'stockholm' => [
        'name' => 'Stockholm',
        'preview_background_color' => '#f3f4f6',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#111827',
            'description_color' => '#6b7280',
            'background_color' => '#ffffff',
            'button_color' => '#ffffff',
            'button_background_color' => '#111827',
            'close_button_color' => '#374151',
            'border_color' => '#e5e7eb',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f9fafb',
            'dark_mode_description_color' => '#9ca3af',
            'dark_mode_background_color' => '#111827',
            'dark_mode_button_color' => '#111827',
            'dark_mode_button_background_color' => '#f9fafb',
            'dark_mode_close_button_color' => '#d1d5db',
            'dark_mode_border_color' => '#374151',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'milan' => [
        'name' => 'Milan',
        'preview_background_color' => '#f8fafc',
        'settings' => [
            'font' => 'Helvetica',
            'title_color' => '#020617',
            'description_color' => '#475569',
            'background_color' => '#ffffff',
            'button_color' => '#ffffff',
            'button_background_color' => '#020617',
            'close_button_color' => '#334155',
            'border_color' => '#e2e8f0',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#020617',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f8fafc',
            'dark_mode_description_color' => '#94a3b8',
            'dark_mode_background_color' => '#020617',
            'dark_mode_button_color' => '#020617',
            'dark_mode_button_background_color' => '#f8fafc',
            'dark_mode_close_button_color' => '#cbd5e1',
            'dark_mode_border_color' => '#1e293b',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'copenhagen' => [
        'name' => 'Copenhagen',
        'preview_background_color' => '#e7e5e4',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#292524',
            'description_color' => '#78716c',
            'background_color' => '#fafaf9',
            'button_color' => '#ffffff',
            'button_background_color' => '#44403c',
            'close_button_color' => '#57534e',
            'border_color' => '#d6d3d1',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => '',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fafaf9',
            'dark_mode_description_color' => '#a8a29e',
            'dark_mode_background_color' => '#1c1917',
            'dark_mode_button_color' => '#292524',
            'dark_mode_button_background_color' => '#d6d3d1',
            'dark_mode_close_button_color' => '#d6d3d1',
            'dark_mode_border_color' => '#44403c',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'zurich' => [
        'name' => 'Zurich',
        'preview_background_color' => '#e2e8f0',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#0f172a',
            'description_color' => '#64748b',
            'background_color' => '#f8fafc',
            'button_color' => '#ffffff',
            'button_background_color' => '#2563eb',
            'close_button_color' => '#334155',
            'border_color' => '#cbd5e1',
            'internal_padding' => 12,
            'background_blur' => 0,
            'shadow' => '',
            'shadow_color' => '#0f172a',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f8fafc',
            'dark_mode_description_color' => '#94a3b8',
            'dark_mode_background_color' => '#0f172a',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#2563eb',
            'dark_mode_close_button_color' => '#cbd5e1',
            'dark_mode_border_color' => '#334155',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'helsinki' => [
        'name' => 'Helsinki',
        'preview_background_color' => '#e0e7ff',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#1e1b4b',
            'description_color' => '#54587a',
            'background_color' => '#eef2ff',
            'button_color' => '#ffffff',
            'button_background_color' => '#4f46e5',
            'close_button_color' => '#4338ca',
            'border_color' => '#c7d2fe',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#1e1b4b',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#eef2ff',
            'dark_mode_description_color' => '#c7d2fe',
            'dark_mode_background_color' => '#1e1b4b',
            'dark_mode_button_color' => '#1e1b4b',
            'dark_mode_button_background_color' => '#818cf8',
            'dark_mode_close_button_color' => '#c7d2fe',
            'dark_mode_border_color' => '#4338ca',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'berlin' => [
        'name' => 'Berlin',
        'preview_background_color' => '#e7e5e4',
        'settings' => [
            'font' => 'Helvetica',
            'title_color' => '#1c1917',
            'description_color' => '#6f625b',
            'background_color' => '#faf7f2',
            'button_color' => '#ffffff',
            'button_background_color' => '#c2410c',
            'close_button_color' => '#1e3a8a',
            'border_color' => '#d6d3d1',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#1c1917',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#faf7f2',
            'dark_mode_description_color' => '#a8a29e',
            'dark_mode_background_color' => '#1c1917',
            'dark_mode_button_color' => '#1c1917',
            'dark_mode_button_background_color' => '#ea580c',
            'dark_mode_close_button_color' => '#bfdbfe',
            'dark_mode_border_color' => '#44403c',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'cape_town' => [
        'name' => 'Cape Town',
        'preview_background_color' => '#e8eadf',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#2f3e2f',
            'description_color' => '#697466',
            'background_color' => '#fafaf5',
            'button_color' => '#ffffff',
            'button_background_color' => '#3f6212',
            'close_button_color' => '#4d5d42',
            'border_color' => '#d6d9ca',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#2f3e2f',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fafaf5',
            'dark_mode_description_color' => '#a8b3a2',
            'dark_mode_background_color' => '#1f2b1f',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#4d7c0f',
            'dark_mode_close_button_color' => '#d6d9ca',
            'dark_mode_border_color' => '#4d5d42',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'kyoto' => [
        'name' => 'Kyoto',
        'preview_background_color' => '#ecfccb',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#365314',
            'description_color' => '#627449',
            'background_color' => '#f7fee7',
            'button_color' => '#ffffff',
            'button_background_color' => '#4d7c0f',
            'close_button_color' => '#3f6212',
            'border_color' => '#bef264',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => '',
            'shadow_color' => '#365314',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f7fee7',
            'dark_mode_description_color' => '#bef264',
            'dark_mode_background_color' => '#1a2e05',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#4d7c0f',
            'dark_mode_close_button_color' => '#ecfccb',
            'dark_mode_border_color' => '#3f6212',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'amsterdam' => [
        'name' => 'Amsterdam',
        'preview_background_color' => '#ccfbf1',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#134e4a',
            'description_color' => '#41736e',
            'background_color' => '#f0fdfa',
            'button_color' => '#ffffff',
            'button_background_color' => '#0f766e',
            'close_button_color' => '#115e59',
            'border_color' => '#99f6e4',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => '',
            'shadow_color' => '#134e4a',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f0fdfa',
            'dark_mode_description_color' => '#5eead4',
            'dark_mode_background_color' => '#042f2e',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#0f766e',
            'dark_mode_close_button_color' => '#ccfbf1',
            'dark_mode_border_color' => '#115e59',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'miami' => [
        'name' => 'Miami',
        'preview_background_color' => '#cffafe',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#164e63',
            'description_color' => '#3f7180',
            'background_color' => '#ecfeff',
            'button_color' => '#ffffff',
            'button_background_color' => '#0e7490',
            'close_button_color' => '#155e75',
            'border_color' => '#a5f3fc',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#164e63',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#ecfeff',
            'dark_mode_description_color' => '#a5f3fc',
            'dark_mode_background_color' => '#083344',
            'dark_mode_button_color' => '#082f49',
            'dark_mode_button_background_color' => '#22d3ee',
            'dark_mode_close_button_color' => '#cffafe',
            'dark_mode_border_color' => '#155e75',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'athens' => [
        'name' => 'Athens',
        'preview_background_color' => '#fef9c3',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#713f12',
            'description_color' => '#715b18',
            'background_color' => '#fefce8',
            'button_color' => '#ffffff',
            'button_background_color' => '#a16207',
            'close_button_color' => '#854d0e',
            'border_color' => '#fde68a',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#713f12',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fef9c3',
            'dark_mode_description_color' => '#fde68a',
            'dark_mode_background_color' => '#422006',
            'dark_mode_button_color' => '#422006',
            'dark_mode_button_background_color' => '#facc15',
            'dark_mode_close_button_color' => '#fef3c7',
            'dark_mode_border_color' => '#854d0e',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'barcelona' => [
        'name' => 'Barcelona',
        'preview_background_color' => '#fef3c7',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#78350f',
            'description_color' => '#8c672f',
            'background_color' => '#fffbeb',
            'button_color' => '#ffffff',
            'button_background_color' => '#2563eb',
            'close_button_color' => '#92400e',
            'border_color' => '#fcd34d',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#78350f',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fffbeb',
            'dark_mode_description_color' => '#fcd34d',
            'dark_mode_background_color' => '#451a03',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#2563eb',
            'dark_mode_close_button_color' => '#fef3c7',
            'dark_mode_border_color' => '#92400e',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'lisbon' => [
        'name' => 'Lisbon',
        'preview_background_color' => '#fff7ed',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#7c2d12',
            'description_color' => '#8f5a46',
            'background_color' => '#fff7ed',
            'button_color' => '#ffffff',
            'button_background_color' => '#c2410c',
            'close_button_color' => '#9a3412',
            'border_color' => '#fed7aa',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#7c2d12',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#ffedd5',
            'dark_mode_description_color' => '#fdba74',
            'dark_mode_background_color' => '#431407',
            'dark_mode_button_color' => '#1c1917',
            'dark_mode_button_background_color' => '#ea580c',
            'dark_mode_close_button_color' => '#fed7aa',
            'dark_mode_border_color' => '#9a3412',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'marrakech' => [
        'name' => 'Marrakech',
        'preview_background_color' => '#f3e5d8',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#5c2e20',
            'description_color' => '#7d5b4f',
            'background_color' => '#fffaf5',
            'button_color' => '#ffffff',
            'button_background_color' => '#9a3412',
            'close_button_color' => '#7c2d12',
            'border_color' => '#e7c4aa',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#5c2e20',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fff7ed',
            'dark_mode_description_color' => '#d6a98c',
            'dark_mode_background_color' => '#32170f',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#c2410c',
            'dark_mode_close_button_color' => '#e7c4aa',
            'dark_mode_border_color' => '#7c2d12',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'montreal' => [
        'name' => 'Montreal',
        'preview_background_color' => '#fee2e2',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#7f1d1d',
            'description_color' => '#994c4c',
            'background_color' => '#fef2f2',
            'button_color' => '#ffffff',
            'button_background_color' => '#b91c1c',
            'close_button_color' => '#991b1b',
            'border_color' => '#fecaca',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#7f1d1d',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fef2f2',
            'dark_mode_description_color' => '#fca5a5',
            'dark_mode_background_color' => '#450a0a',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#dc2626',
            'dark_mode_close_button_color' => '#fecaca',
            'dark_mode_border_color' => '#991b1b',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'paris' => [
        'name' => 'Paris',
        'preview_background_color' => '#ffe4e6',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#4c0519',
            'description_color' => '#8f4559',
            'background_color' => '#fff1f2',
            'button_color' => '#ffffff',
            'button_background_color' => '#be123c',
            'close_button_color' => '#9f1239',
            'border_color' => '#fecdd3',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#4c0519',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fff1f2',
            'dark_mode_description_color' => '#fda4af',
            'dark_mode_background_color' => '#4c0519',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#e11d48',
            'dark_mode_close_button_color' => '#fecdd3',
            'dark_mode_border_color' => '#9f1239',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'prague' => [
        'name' => 'Prague',
        'preview_background_color' => '#e9d5ff',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#37304f',
            'description_color' => '#5f586d',
            'background_color' => '#f8f7ff',
            'button_color' => '#ffffff',
            'button_background_color' => '#5750a6',
            'close_button_color' => '#4c458f',
            'border_color' => '#ddd6fe',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#37304f',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f5f3ff',
            'dark_mode_description_color' => '#c4bdd7',
            'dark_mode_background_color' => '#211c32',
            'dark_mode_button_color' => '#211c32',
            'dark_mode_button_background_color' => '#a78bfa',
            'dark_mode_close_button_color' => '#ddd6fe',
            'dark_mode_border_color' => '#4c458f',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'vienna' => [
        'name' => 'Vienna',
        'preview_background_color' => '#ede9fe',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#4c1d95',
            'description_color' => '#735d91',
            'background_color' => '#f5f3ff',
            'button_color' => '#ffffff',
            'button_background_color' => '#6d28d9',
            'close_button_color' => '#5b21b6',
            'border_color' => '#ddd6fe',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#4c1d95',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f5f3ff',
            'dark_mode_description_color' => '#c4b5fd',
            'dark_mode_background_color' => '#2e1065',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#7c3aed',
            'dark_mode_close_button_color' => '#ddd6fe',
            'dark_mode_border_color' => '#5b21b6',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'new_york' => [
        'name' => 'New York',
        'preview_background_color' => '#08090c',
        'settings' => [
            'font' => 'Helvetica',
            'title_color' => '#f8fafc',
            'description_color' => '#929aa8',
            'background_color' => '#111318',
            'button_color' => '#111318',
            'button_background_color' => '#f8fafc',
            'close_button_color' => '#d1d5db',
            'border_color' => '#343a46',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f8fafc',
            'dark_mode_description_color' => '#929aa8',
            'dark_mode_background_color' => '#111318',
            'dark_mode_button_color' => '#111318',
            'dark_mode_button_background_color' => '#f8fafc',
            'dark_mode_close_button_color' => '#d1d5db',
            'dark_mode_border_color' => '#343a46',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'tokyo' => [
        'name' => 'Tokyo',
        'preview_background_color' => '#030712',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#f9fafb',
            'description_color' => '#8b95a5',
            'background_color' => '#111827',
            'button_color' => '#082f49',
            'button_background_color' => '#22d3ee',
            'close_button_color' => '#d1d5db',
            'border_color' => '#374151',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f9fafb',
            'dark_mode_description_color' => '#8b95a5',
            'dark_mode_background_color' => '#111827',
            'dark_mode_button_color' => '#082f49',
            'dark_mode_button_background_color' => '#22d3ee',
            'dark_mode_close_button_color' => '#d1d5db',
            'dark_mode_border_color' => '#374151',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'oslo' => [
        'name' => 'Oslo',
        'preview_background_color' => '#0f172a',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#e0e7ff',
            'description_color' => '#a5b4fc',
            'background_color' => '#111827',
            'button_color' => '#111827',
            'button_background_color' => '#818cf8',
            'close_button_color' => '#c7d2fe',
            'border_color' => '#312e81',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#e0e7ff',
            'dark_mode_description_color' => '#a5b4fc',
            'dark_mode_background_color' => '#111827',
            'dark_mode_button_color' => '#111827',
            'dark_mode_button_background_color' => '#818cf8',
            'dark_mode_close_button_color' => '#c7d2fe',
            'dark_mode_border_color' => '#312e81',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'seoul' => [
        'name' => 'Seoul',
        'preview_background_color' => '#09090b',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#fafafa',
            'description_color' => '#8b8b95',
            'background_color' => '#18181b',
            'button_color' => '#ffffff',
            'button_background_color' => '#7c3aed',
            'close_button_color' => '#d4d4d8',
            'border_color' => '#3f3f46',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fafafa',
            'dark_mode_description_color' => '#8b8b95',
            'dark_mode_background_color' => '#18181b',
            'dark_mode_button_color' => '#ffffff',
            'dark_mode_button_background_color' => '#7c3aed',
            'dark_mode_close_button_color' => '#d4d4d8',
            'dark_mode_border_color' => '#3f3f46',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'singapore' => [
        'name' => 'Singapore',
        'preview_background_color' => '#081512',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#f0fdfa',
            'description_color' => '#7f9f95',
            'background_color' => '#0f1f1b',
            'button_color' => '#052e16',
            'button_background_color' => '#34d399',
            'close_button_color' => '#d1fae5',
            'border_color' => '#2b5145',
            'internal_padding' => 14,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f0fdfa',
            'dark_mode_description_color' => '#7f9f95',
            'dark_mode_background_color' => '#0f1f1b',
            'dark_mode_button_color' => '#052e16',
            'dark_mode_button_background_color' => '#34d399',
            'dark_mode_close_button_color' => '#d1fae5',
            'dark_mode_border_color' => '#2b5145',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'dublin' => [
        'name' => 'Dublin',
        'preview_background_color' => '#111827',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#ecfdf5',
            'description_color' => '#9ca3af',
            'background_color' => '#1f2937',
            'button_color' => '#052e16',
            'button_background_color' => '#4ade80',
            'close_button_color' => '#bbf7d0',
            'border_color' => '#374151',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#ecfdf5',
            'dark_mode_description_color' => '#9ca3af',
            'dark_mode_background_color' => '#1f2937',
            'dark_mode_button_color' => '#052e16',
            'dark_mode_button_background_color' => '#4ade80',
            'dark_mode_close_button_color' => '#bbf7d0',
            'dark_mode_border_color' => '#374151',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'istanbul' => [
        'name' => 'Istanbul',
        'preview_background_color' => '#042f2e',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#f0fdfa',
            'description_color' => '#99f6e4',
            'background_color' => '#0f2f2e',
            'button_color' => '#111827',
            'button_background_color' => '#f97316',
            'close_button_color' => '#fed7aa',
            'border_color' => '#115e59',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#f0fdfa',
            'dark_mode_description_color' => '#99f6e4',
            'dark_mode_background_color' => '#0f2f2e',
            'dark_mode_button_color' => '#111827',
            'dark_mode_button_background_color' => '#f97316',
            'dark_mode_close_button_color' => '#fed7aa',
            'dark_mode_border_color' => '#115e59',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'monaco' => [
        'name' => 'Monaco',
        'preview_background_color' => '#0a0a0a',
        'settings' => [
            'font' => 'Helvetica',
            'title_color' => '#fef3c7',
            'description_color' => '#d6c38f',
            'background_color' => '#0a0a0a',
            'button_color' => '#0a0a0a',
            'button_background_color' => '#facc15',
            'close_button_color' => '#fef08a',
            'border_color' => '#3f3a2a',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fef3c7',
            'dark_mode_description_color' => '#d6c38f',
            'dark_mode_background_color' => '#0a0a0a',
            'dark_mode_button_color' => '#0a0a0a',
            'dark_mode_button_background_color' => '#facc15',
            'dark_mode_close_button_color' => '#fef08a',
            'dark_mode_border_color' => '#3f3a2a',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'florence' => [
        'name' => 'Florence',
        'preview_background_color' => '#1f0a13',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#fff1f2',
            'description_color' => '#fda4af',
            'background_color' => '#4c0519',
            'button_color' => '#4c0519',
            'button_background_color' => '#fb7185',
            'close_button_color' => '#fecdd3',
            'border_color' => '#9f1239',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fff1f2',
            'dark_mode_description_color' => '#fda4af',
            'dark_mode_background_color' => '#4c0519',
            'dark_mode_button_color' => '#4c0519',
            'dark_mode_button_background_color' => '#fb7185',
            'dark_mode_close_button_color' => '#fecdd3',
            'dark_mode_border_color' => '#9f1239',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'dubai' => [
        'name' => 'Dubai',
        'preview_background_color' => '#0c0a09',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#fef3c7',
            'description_color' => '#a8a29e',
            'background_color' => '#1c1917',
            'button_color' => '#451a03',
            'button_background_color' => '#f59e0b',
            'close_button_color' => '#e7e5e4',
            'border_color' => '#57534e',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fef3c7',
            'dark_mode_description_color' => '#a8a29e',
            'dark_mode_background_color' => '#1c1917',
            'dark_mode_button_color' => '#451a03',
            'dark_mode_button_background_color' => '#f59e0b',
            'dark_mode_close_button_color' => '#e7e5e4',
            'dark_mode_border_color' => '#57534e',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],

    'rio_de_janeiro' => [
        'name' => 'Rio de Janeiro',
        'preview_background_color' => '#0f172a',
        'settings' => [
            'font' => 'inherit',
            'title_color' => '#fefce8',
            'description_color' => '#b4bdd3',
            'background_color' => '#172554',
            'button_color' => '#431407',
            'button_background_color' => '#fb923c',
            'close_button_color' => '#fef9c3',
            'border_color' => '#334a8a',
            'internal_padding' => 15,
            'background_blur' => 0,
            'shadow' => 'feather',
            'shadow_color' => '#000000',
            'border_radius' => 'highly_rounded',
            'border_width' => 1,
            'dark_mode_title_color' => '#fefce8',
            'dark_mode_description_color' => '#b4bdd3',
            'dark_mode_background_color' => '#172554',
            'dark_mode_button_color' => '#431407',
            'dark_mode_button_background_color' => '#fb923c',
            'dark_mode_close_button_color' => '#fef9c3',
            'dark_mode_border_color' => '#334a8a',
            'dark_mode_shadow_color' => '#000000',
        ],
    ],
];

/* Add the dedicated settings used only by certain notification types */
$default_settings = $themes['stockholm']['settings'];

foreach($themes as $key => $theme) {
    $settings = array_merge($default_settings, $theme['settings']);

    $themes[$key]['settings'] = array_merge([
        'date_color' => $settings['description_color'],
        'number_background_color' => $settings['button_background_color'],
        'number_color' => $settings['button_color'],
        'pulse_background_color' => $settings['button_background_color'],
        'content_title_color' => $settings['title_color'],
        'content_description_color' => $settings['description_color'],
        'time_background_color' => $settings['button_background_color'],
        'time_color' => $settings['button_color'],
        'coupon_code_background_color' => $settings['button_background_color'],
        'coupon_code_border_color' => $settings['button_background_color'],
        'coupon_code_color' => $settings['button_color'],
        'categories_title_color' => $settings['title_color'],
        'categories_description_color' => $settings['description_color'],
        'categories_links_background_color' => $settings['background_color'],
        'categories_links_border_color' => $settings['border_color'],
        'categories_links_title_color' => $settings['title_color'],
        'categories_links_description_color' => $settings['description_color'],
        /* Help center colors */
        'badge_background_color' => $settings['background_color'],
        'badge_color' => $settings['title_color'],
        'hint_background_color' => $settings['title_color'],
        'hint_color' => $settings['background_color'],
        'item_question_color' => $settings['title_color'],
        'item_answer_color' => $settings['description_color'],
        'item_background_color' => $settings['background_color'],
        'item_border_color' => $settings['border_color'],
        'header_background_color' => $settings['button_background_color'],
        'header_agent_name_color' => $settings['button_color'],
        'header_agent_description_color' => $settings['button_color'],
        'content_background_color' => $settings['background_color'],
        'content_agent_name_color' => $settings['title_color'],
        'content_agent_message_color' => $settings['title_color'],
        'content_agent_message_background_color' => $settings['border_color'],
        'footer_background_color' => $settings['background_color'],
        'footer_button_background_color' => $settings['button_background_color'],
        'footer_button_color' => $settings['button_color'],
        'dark_mode_date_color' => $settings['dark_mode_description_color'],
        'dark_mode_number_background_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_number_color' => $settings['dark_mode_button_color'],
        'dark_mode_pulse_background_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_content_title_color' => $settings['dark_mode_title_color'],
        'dark_mode_content_description_color' => $settings['dark_mode_description_color'],
        'dark_mode_time_background_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_time_color' => $settings['dark_mode_button_color'],
        'dark_mode_coupon_code_background_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_coupon_code_border_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_coupon_code_color' => $settings['dark_mode_button_color'],
        'dark_mode_categories_title_color' => $settings['dark_mode_title_color'],
        'dark_mode_categories_description_color' => $settings['dark_mode_description_color'],
        'dark_mode_categories_links_background_color' => $settings['dark_mode_background_color'],
        'dark_mode_categories_links_border_color' => $settings['dark_mode_border_color'],
        'dark_mode_categories_links_title_color' => $settings['dark_mode_title_color'],
        'dark_mode_categories_links_description_color' => $settings['dark_mode_description_color'],
        /* Help center colors */
        'dark_mode_badge_background_color' => $settings['dark_mode_background_color'],
        'dark_mode_badge_color' => $settings['dark_mode_title_color'],
        'dark_mode_hint_background_color' => $settings['dark_mode_title_color'],
        'dark_mode_hint_color' => $settings['dark_mode_background_color'],
        'dark_mode_item_question_color' => $settings['dark_mode_title_color'],
        'dark_mode_item_answer_color' => $settings['dark_mode_description_color'],
        'dark_mode_item_background_color' => $settings['dark_mode_background_color'],
        'dark_mode_item_border_color' => $settings['dark_mode_border_color'],
        'dark_mode_header_background_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_header_agent_name_color' => $settings['dark_mode_button_color'],
        'dark_mode_header_agent_description_color' => $settings['dark_mode_button_color'],
        'dark_mode_content_background_color' => $settings['dark_mode_background_color'],
        'dark_mode_content_agent_name_color' => $settings['dark_mode_title_color'],
        'dark_mode_content_agent_message_color' => $settings['dark_mode_title_color'],
        'dark_mode_content_agent_message_background_color' => $settings['dark_mode_border_color'],
        'dark_mode_footer_background_color' => $settings['dark_mode_background_color'],
        'dark_mode_footer_button_background_color' => $settings['dark_mode_button_background_color'],
        'dark_mode_footer_button_color' => $settings['dark_mode_button_color'],
    ], $settings);
}

return $themes;
