<?php

namespace Modules\AppLinkBio\Support;

class LinkBioTemplateCatalog
{
    public static function all(): array
    {
        return [
            [
                'key' => 'aurora',
                'label' => 'Aurora',
                'description' => 'Gradient creator card with dark glossy blocks.',
                'category' => 'Featured',
                'preview' => 'linear-gradient(135deg, #ff6b2c 0%, #e83f6f 48%, #232946 100%)',
                'theme' => [
                    'page_bg' => 'radial-gradient(circle at top, rgba(37,99,235,0.20), transparent 28%), #0f172a',
                    'shell_bg' => 'linear-gradient(180deg, rgba(17,24,39,0.94), rgba(17,24,39,0.82))',
                    'surface_bg' => 'linear-gradient(180deg, rgba(255,255,255,0.10), rgba(255,255,255,0.04))',
                    'surface_border' => 'rgba(255,255,255,0.14)',
                    'text' => '#f8fafc',
                    'muted' => 'rgba(248,250,252,0.72)',
                    'surface_text' => '#f8fafc',
                    'surface_muted' => 'rgba(248,250,252,0.72)',
                    'button_bg' => '#2563eb',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'studio-pro',
                'label' => 'Studio Pro',
                'description' => 'Polished creator profile with crisp contrast and premium action buttons.',
                'category' => 'Professional',
                'preview' => 'linear-gradient(135deg, #0f172a 0%, #1d4ed8 46%, #f8fafc 46%, #ffffff 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #eaf2ff 0%, #f8fafc 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #0f172a 0%, #111827 40%, #ffffff 40%, #ffffff 100%)',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(37,99,235,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.78)',
                    'surface_text' => '#0f172a',
                    'surface_muted' => '#64748b',
                    'button_bg' => '#2563eb',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'minimal',
                'label' => 'Minimal',
                'description' => 'Clean editorial layout with light surfaces.',
                'category' => 'Professional',
                'preview' => 'linear-gradient(135deg, #ffffff 0%, #f8fafc 50%, #fed7aa 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #eef4ff 0%, #f8fafc 100%)',
                    'shell_bg' => '#ffffff',
                    'surface_bg' => '#f8fafc',
                    'surface_border' => 'rgba(148,163,184,0.22)',
                    'text' => '#0f172a',
                    'muted' => '#64748b',
                    'surface_text' => '#0f172a',
                    'surface_muted' => '#64748b',
                    'button_bg' => '#0f172a',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'spotlight',
                'label' => 'Spotlight',
                'description' => 'Bold spotlight frame for launches and campaigns.',
                'category' => 'Creator',
                'preview' => 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 48%, #22d3ee 100%)',
                'theme' => [
                    'page_bg' => 'radial-gradient(circle at top left, rgba(34,211,238,0.18), transparent 30%), #0b1120',
                    'shell_bg' => 'linear-gradient(180deg, #1d4ed8 0%, #2563eb 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.12)',
                    'surface_border' => 'rgba(255,255,255,0.18)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.76)',
                    'surface_text' => '#ffffff',
                    'surface_muted' => 'rgba(255,255,255,0.76)',
                    'button_bg' => '#22d3ee',
                    'button_text' => '#0f172a',
                ],
            ],
            [
                'key' => 'paper-stack',
                'label' => 'Paper Stack',
                'description' => 'Soft paper-inspired blocks for personal pages.',
                'category' => 'Lifestyle',
                'preview' => 'linear-gradient(135deg, #fef3c7 0%, #fed7aa 50%, #fff7ed 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fff7ed 0%, #fffbeb 100%)',
                    'shell_bg' => '#fffefc',
                    'surface_bg' => '#fff7ed',
                    'surface_border' => 'rgba(251,146,60,0.24)',
                    'text' => '#7c2d12',
                    'muted' => '#9a3412',
                    'surface_text' => '#7c2d12',
                    'surface_muted' => '#9a3412',
                    'button_bg' => '#f97316',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'travel-cards',
                'label' => 'Travel Cards',
                'description' => 'Playful travel card layout with bright cards.',
                'category' => 'Travel',
                'preview' => 'linear-gradient(180deg, #8b5cf6 0%, #d946ef 58%, #f59e0b 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #dbeafe 0%, #bfdbfe 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #9333ea 0%, #f472b6 42%, #ffffff 42%, #ffffff 100%)',
                    'surface_bg' => '#fff7ed',
                    'surface_border' => 'rgba(251,146,60,0.20)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.78)',
                    'surface_text' => '#7c2d12',
                    'surface_muted' => '#9a3412',
                    'button_bg' => '#7c3aed',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'pro-dark',
                'label' => 'Pro Dark',
                'description' => 'Dark premium look for serious brands.',
                'category' => 'Professional',
                'preview' => 'linear-gradient(135deg, #020617 0%, #111827 58%, #d4a500 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #020617 0%, #111827 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #0f172a 0%, #111827 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.06)',
                    'surface_border' => 'rgba(255,255,255,0.10)',
                    'text' => '#f8fafc',
                    'muted' => 'rgba(248,250,252,0.72)',
                    'surface_text' => '#f8fafc',
                    'surface_muted' => 'rgba(248,250,252,0.72)',
                    'button_bg' => '#d4a500',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'social-wave',
                'label' => 'Social Wave',
                'description' => 'Social-first gradient page with playful chips.',
                'category' => 'Creator',
                'preview' => 'linear-gradient(180deg, #4f46e5 0%, #a855f7 48%, #ffffff 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #dbeafe 0%, #eef2ff 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #8b5cf6 0%, #d946ef 48%, #ffffff 48%, #ffffff 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.88)',
                    'surface_border' => 'rgba(79,70,229,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.82)',
                    'surface_text' => '#1f2937',
                    'surface_muted' => '#64748b',
                    'button_bg' => '#4f46e5',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'soft-beige',
                'label' => 'Soft Beige',
                'description' => 'Warm neutral palette for experts and lifestyle pages.',
                'category' => 'Lifestyle',
                'preview' => 'linear-gradient(180deg, #efe2d1 0%, #e7d4bd 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f8fafc 0%, #f3f4f6 100%)',
                    'shell_bg' => '#f5ede2',
                    'surface_bg' => 'rgba(255,255,255,0.54)',
                    'surface_border' => 'rgba(120,83,49,0.16)',
                    'text' => '#3f2d1f',
                    'muted' => '#6b4f3a',
                    'surface_text' => '#3f2d1f',
                    'surface_muted' => '#6b4f3a',
                    'button_bg' => '#7c3f1d',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'promo-orange',
                'label' => 'Promo Orange',
                'description' => 'High-energy promo page for launches and campaigns.',
                'category' => 'Business',
                'preview' => 'linear-gradient(135deg, #fb923c 0%, #f97316 50%, #ef4444 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #ffedd5 0%, #fff7ed 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #fb923c 0%, #fed7aa 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.86)',
                    'surface_border' => 'rgba(249,115,22,0.18)',
                    'text' => '#7c2d12',
                    'muted' => '#9a3412',
                    'surface_text' => '#7c2d12',
                    'surface_muted' => '#9a3412',
                    'button_bg' => '#ef4444',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'affiliate-tablet',
                'label' => 'Affiliate Tablet',
                'description' => 'Tablet-style affiliate profile with strong CTA focus.',
                'category' => 'Business',
                'preview' => 'linear-gradient(180deg, #6b6470 0%, #f3b27a 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f1f5f9 0%, #e2e8f0 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #6b6470 0%, #f3b27a 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.18)',
                    'surface_border' => 'rgba(255,255,255,0.24)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.82)',
                    'surface_text' => '#ffffff',
                    'surface_muted' => 'rgba(255,255,255,0.82)',
                    'button_bg' => '#6b6470',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'creator-sky',
                'label' => 'Creator Sky',
                'description' => 'Bright creator profile with modern blue surfaces.',
                'category' => 'Featured',
                'preview' => 'linear-gradient(180deg, #0ea5e9 0%, #2563eb 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #eff6ff 0%, #dbeafe 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #0ea5e9 0%, #2563eb 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.10)',
                    'surface_border' => 'rgba(255,255,255,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.82)',
                    'surface_text' => '#ffffff',
                    'surface_muted' => 'rgba(255,255,255,0.82)',
                    'button_bg' => '#0ea5e9',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'mono-editorial',
                'label' => 'Mono Editorial',
                'description' => 'Sharp black-and-white layout for writers and portfolios.',
                'category' => 'Professional',
                'preview' => 'linear-gradient(135deg, #111827 0%, #111827 45%, #f9fafb 45%, #ffffff 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f3f4f6 0%, #ffffff 100%)',
                    'shell_bg' => '#ffffff',
                    'surface_bg' => '#f9fafb',
                    'surface_border' => 'rgba(17,24,39,0.14)',
                    'text' => '#111827',
                    'muted' => '#4b5563',
                    'surface_text' => '#111827',
                    'surface_muted' => '#6b7280',
                    'button_bg' => '#111827',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'neon-night',
                'label' => 'Neon Night',
                'description' => 'High-contrast neon profile for music, gaming, and nightlife.',
                'category' => 'Creator',
                'preview' => 'linear-gradient(135deg, #050816 0%, #0f172a 42%, #00f5d4 74%, #f15bb5 100%)',
                'theme' => [
                    'page_bg' => 'radial-gradient(circle at top, rgba(0,245,212,0.16), transparent 32%), #050816',
                    'shell_bg' => 'linear-gradient(180deg, #0b1020 0%, #111827 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.07)',
                    'surface_border' => 'rgba(0,245,212,0.24)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.72)',
                    'surface_text' => '#ffffff',
                    'surface_muted' => 'rgba(255,255,255,0.70)',
                    'button_bg' => '#00f5d4',
                    'button_text' => '#061018',
                ],
            ],
            [
                'key' => 'sage-calm',
                'label' => 'Sage Calm',
                'description' => 'Soft green wellness profile for coaches and health creators.',
                'category' => 'Lifestyle',
                'preview' => 'linear-gradient(135deg, #d9f99d 0%, #86efac 44%, #31572c 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f0fdf4 0%, #ecfdf5 100%)',
                    'shell_bg' => '#f7fee7',
                    'surface_bg' => 'rgba(255,255,255,0.70)',
                    'surface_border' => 'rgba(34,197,94,0.18)',
                    'text' => '#1f3d2b',
                    'muted' => '#3f6212',
                    'surface_text' => '#1f3d2b',
                    'surface_muted' => '#4d7c0f',
                    'button_bg' => '#15803d',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'rose-studio',
                'label' => 'Rose Studio',
                'description' => 'Warm beauty and personal brand template with soft rose tones.',
                'category' => 'Beauty',
                'preview' => 'linear-gradient(135deg, #fff1f2 0%, #fb7185 54%, #881337 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fff1f2 0%, #ffe4e6 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #be123c 0%, #fb7185 38%, #fff7f7 38%, #fff7f7 100%)',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(190,18,60,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.78)',
                    'surface_text' => '#881337',
                    'surface_muted' => '#9f1239',
                    'button_bg' => '#be123c',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'forest-pro',
                'label' => 'Forest Pro',
                'description' => 'Deep forest palette for premium consultants and makers.',
                'category' => 'Professional',
                'preview' => 'linear-gradient(135deg, #052e16 0%, #166534 58%, #d9f99d 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #022c22 0%, #064e3b 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #052e16 0%, #14532d 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.08)',
                    'surface_border' => 'rgba(217,249,157,0.20)',
                    'text' => '#f7fee7',
                    'muted' => 'rgba(247,254,231,0.74)',
                    'surface_text' => '#f7fee7',
                    'surface_muted' => 'rgba(247,254,231,0.70)',
                    'button_bg' => '#bef264',
                    'button_text' => '#14532d',
                ],
            ],
            [
                'key' => 'coffee-note',
                'label' => 'Coffee Note',
                'description' => 'Editorial warm cafe look for newsletters and local brands.',
                'category' => 'Business',
                'preview' => 'linear-gradient(135deg, #fff7ed 0%, #d6a36a 48%, #5c4033 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fffbeb 0%, #fef3c7 100%)',
                    'shell_bg' => '#fff7ed',
                    'surface_bg' => 'rgba(255,255,255,0.66)',
                    'surface_border' => 'rgba(92,64,51,0.16)',
                    'text' => '#4a2e23',
                    'muted' => '#7c4a2d',
                    'surface_text' => '#4a2e23',
                    'surface_muted' => '#7c4a2d',
                    'button_bg' => '#5c4033',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'ocean-clean',
                'label' => 'Ocean Clean',
                'description' => 'Fresh ocean layout for travel guides and clean brands.',
                'category' => 'Travel',
                'preview' => 'linear-gradient(135deg, #ecfeff 0%, #06b6d4 48%, #0e7490 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #ecfeff 0%, #cffafe 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #06b6d4 0%, #0e7490 42%, #ffffff 42%, #ffffff 100%)',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(14,116,144,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.82)',
                    'surface_text' => '#164e63',
                    'surface_muted' => '#0e7490',
                    'button_bg' => '#0891b2',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'sunset-bold',
                'label' => 'Sunset Bold',
                'description' => 'Punchy sunset gradient for launches and creator campaigns.',
                'category' => 'Creator',
                'preview' => 'linear-gradient(135deg, #facc15 0%, #fb923c 42%, #e11d48 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fff7ed 0%, #ffe4e6 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #f97316 0%, #e11d48 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.18)',
                    'surface_border' => 'rgba(255,255,255,0.30)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.80)',
                    'surface_text' => '#ffffff',
                    'surface_muted' => 'rgba(255,255,255,0.78)',
                    'button_bg' => '#facc15',
                    'button_text' => '#7f1d1d',
                ],
            ],
            [
                'key' => 'lavender-grid',
                'label' => 'Lavender Grid',
                'description' => 'Soft lavender creative profile with airy blocks.',
                'category' => 'Artist',
                'preview' => 'linear-gradient(135deg, #faf5ff 0%, #c084fc 52%, #581c87 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #faf5ff 0%, #f3e8ff 100%)',
                    'shell_bg' => '#ffffff',
                    'surface_bg' => '#faf5ff',
                    'surface_border' => 'rgba(126,34,206,0.16)',
                    'text' => '#3b0764',
                    'muted' => '#7e22ce',
                    'surface_text' => '#3b0764',
                    'surface_muted' => '#7e22ce',
                    'button_bg' => '#7e22ce',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'fitness-pulse',
                'label' => 'Fitness Pulse',
                'description' => 'Energetic fitness template with strong CTA contrast.',
                'category' => 'Fitness',
                'preview' => 'linear-gradient(135deg, #111827 0%, #ef4444 48%, #facc15 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #111827 0%, #1f2937 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #111827 0%, #ef4444 100%)',
                    'surface_bg' => 'rgba(255,255,255,0.10)',
                    'surface_border' => 'rgba(255,255,255,0.18)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.76)',
                    'surface_text' => '#ffffff',
                    'surface_muted' => 'rgba(255,255,255,0.72)',
                    'button_bg' => '#facc15',
                    'button_text' => '#111827',
                ],
            ],
            [
                'key' => 'chef-card',
                'label' => 'Chef Card',
                'description' => 'Food creator template with warm red and cream surfaces.',
                'category' => 'Food',
                'preview' => 'linear-gradient(135deg, #fee2e2 0%, #dc2626 52%, #7f1d1d 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fff7ed 0%, #fee2e2 100%)',
                    'shell_bg' => '#fff7ed',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(220,38,38,0.16)',
                    'text' => '#7f1d1d',
                    'muted' => '#991b1b',
                    'surface_text' => '#7f1d1d',
                    'surface_muted' => '#991b1b',
                    'button_bg' => '#dc2626',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'gold-luxe',
                'label' => 'Gold Luxe',
                'description' => 'Luxury brand profile with dark gold accents.',
                'category' => 'Business',
                'preview' => 'linear-gradient(135deg, #171717 0%, #3f3f46 50%, #f5c542 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #09090b 0%, #18181b 100%)',
                    'shell_bg' => '#111111',
                    'surface_bg' => 'rgba(255,255,255,0.06)',
                    'surface_border' => 'rgba(245,197,66,0.20)',
                    'text' => '#fafafa',
                    'muted' => 'rgba(250,250,250,0.70)',
                    'surface_text' => '#fafafa',
                    'surface_muted' => 'rgba(250,250,250,0.68)',
                    'button_bg' => '#f5c542',
                    'button_text' => '#111111',
                ],
            ],
            [
                'key' => 'clean-saas',
                'label' => 'Clean SaaS',
                'description' => 'Calm product and SaaS profile with crisp blue-gray surfaces.',
                'category' => 'Business',
                'preview' => 'linear-gradient(135deg, #f8fafc 0%, #94a3b8 48%, #334155 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%)',
                    'shell_bg' => '#ffffff',
                    'surface_bg' => '#f8fafc',
                    'surface_border' => 'rgba(51,65,85,0.14)',
                    'text' => '#0f172a',
                    'muted' => '#475569',
                    'surface_text' => '#0f172a',
                    'surface_muted' => '#64748b',
                    'button_bg' => '#334155',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'event-pop',
                'label' => 'Event Pop',
                'description' => 'Colorful event page for tickets, schedules, and announcements.',
                'category' => 'Event',
                'preview' => 'linear-gradient(135deg, #22c55e 0%, #facc15 45%, #ec4899 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fefce8 0%, #fdf2f8 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #22c55e 0%, #facc15 48%, #ffffff 48%, #ffffff 100%)',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(236,72,153,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.82)',
                    'surface_text' => '#831843',
                    'surface_muted' => '#9d174d',
                    'button_bg' => '#ec4899',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'aqua-glass',
                'label' => 'Aqua Glass',
                'description' => 'Glassmorphism aqua layout for modern personal pages.',
                'category' => 'Featured',
                'preview' => 'linear-gradient(135deg, #ccfbf1 0%, #14b8a6 48%, #134e4a 100%)',
                'theme' => [
                    'page_bg' => 'radial-gradient(circle at top left, rgba(20,184,166,0.18), transparent 28%), #f0fdfa',
                    'shell_bg' => 'linear-gradient(180deg, rgba(255,255,255,0.86), rgba(240,253,250,0.82))',
                    'surface_bg' => 'rgba(255,255,255,0.64)',
                    'surface_border' => 'rgba(20,184,166,0.22)',
                    'text' => '#134e4a',
                    'muted' => '#0f766e',
                    'surface_text' => '#134e4a',
                    'surface_muted' => '#0f766e',
                    'button_bg' => '#0f766e',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'indie-zine',
                'label' => 'Indie Zine',
                'description' => 'Playful zine-inspired look for artists and makers.',
                'category' => 'Artist',
                'preview' => 'linear-gradient(135deg, #fef08a 0%, #fb7185 46%, #312e81 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fefce8 0%, #fff1f2 100%)',
                    'shell_bg' => '#fef08a',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(49,46,129,0.18)',
                    'text' => '#312e81',
                    'muted' => '#be123c',
                    'surface_text' => '#312e81',
                    'surface_muted' => '#be123c',
                    'button_bg' => '#312e81',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'realty-card',
                'label' => 'Realty Card',
                'description' => 'Trustworthy real estate profile with slate and green accents.',
                'category' => 'Business',
                'preview' => 'linear-gradient(135deg, #f8fafc 0%, #64748b 48%, #166534 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #334155 0%, #166534 42%, #ffffff 42%, #ffffff 100%)',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(22,101,52,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.78)',
                    'surface_text' => '#0f172a',
                    'surface_muted' => '#475569',
                    'button_bg' => '#166534',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'edu-bright',
                'label' => 'Edu Bright',
                'description' => 'Friendly education and course profile with bright contrast.',
                'category' => 'Education',
                'preview' => 'linear-gradient(135deg, #dbeafe 0%, #2563eb 48%, #facc15 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #eff6ff 0%, #dbeafe 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #2563eb 0%, #60a5fa 42%, #ffffff 42%, #ffffff 100%)',
                    'surface_bg' => '#ffffff',
                    'surface_border' => 'rgba(37,99,235,0.16)',
                    'text' => '#ffffff',
                    'muted' => 'rgba(255,255,255,0.82)',
                    'surface_text' => '#1e3a8a',
                    'surface_muted' => '#475569',
                    'button_bg' => '#facc15',
                    'button_text' => '#1e3a8a',
                ],
            ],
            [
                'key' => 'charcoal-red',
                'label' => 'Charcoal Red',
                'description' => 'Bold editorial dark profile with red action accents.',
                'category' => 'Professional',
                'preview' => 'linear-gradient(135deg, #18181b 0%, #3f3f46 58%, #ef4444 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #18181b 0%, #27272a 100%)',
                    'shell_bg' => '#18181b',
                    'surface_bg' => 'rgba(255,255,255,0.07)',
                    'surface_border' => 'rgba(255,255,255,0.12)',
                    'text' => '#fafafa',
                    'muted' => 'rgba(250,250,250,0.72)',
                    'surface_text' => '#fafafa',
                    'surface_muted' => 'rgba(250,250,250,0.68)',
                    'button_bg' => '#ef4444',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'mint-minimal',
                'label' => 'Mint Minimal',
                'description' => 'Quiet minimalist profile with mint action details.',
                'category' => 'Minimal',
                'preview' => 'linear-gradient(135deg, #ffffff 0%, #d1fae5 54%, #10b981 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #f8fafc 0%, #ecfdf5 100%)',
                    'shell_bg' => '#ffffff',
                    'surface_bg' => '#f8fafc',
                    'surface_border' => 'rgba(16,185,129,0.16)',
                    'text' => '#064e3b',
                    'muted' => '#047857',
                    'surface_text' => '#064e3b',
                    'surface_muted' => '#047857',
                    'button_bg' => '#10b981',
                    'button_text' => '#ffffff',
                ],
            ],
            [
                'key' => 'cyber-card',
                'label' => 'Cyber Card',
                'description' => 'Tech-forward profile for developers, streamers, and tools.',
                'category' => 'Tech',
                'preview' => 'linear-gradient(135deg, #020617 0%, #1e40af 50%, #38bdf8 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #020617 0%, #0f172a 100%)',
                    'shell_bg' => 'linear-gradient(180deg, #020617 0%, #172554 100%)',
                    'surface_bg' => 'rgba(56,189,248,0.08)',
                    'surface_border' => 'rgba(56,189,248,0.20)',
                    'text' => '#e0f2fe',
                    'muted' => 'rgba(224,242,254,0.74)',
                    'surface_text' => '#e0f2fe',
                    'surface_muted' => 'rgba(224,242,254,0.70)',
                    'button_bg' => '#38bdf8',
                    'button_text' => '#082f49',
                ],
            ],
            [
                'key' => 'peach-personal',
                'label' => 'Peach Personal',
                'description' => 'Soft personal profile for creators and lifestyle pages.',
                'category' => 'Lifestyle',
                'preview' => 'linear-gradient(135deg, #fff7ed 0%, #fdba74 48%, #fb7185 100%)',
                'theme' => [
                    'page_bg' => 'linear-gradient(180deg, #fff7ed 0%, #ffedd5 100%)',
                    'shell_bg' => '#fff7ed',
                    'surface_bg' => 'rgba(255,255,255,0.72)',
                    'surface_border' => 'rgba(251,113,133,0.16)',
                    'text' => '#7c2d12',
                    'muted' => '#9a3412',
                    'surface_text' => '#7c2d12',
                    'surface_muted' => '#9a3412',
                    'button_bg' => '#fb7185',
                    'button_text' => '#ffffff',
                ],
            ],
        ];
    }

    public static function find(?string $key): array
    {
        $key = trim((string) $key);

        foreach (self::all() as $template) {
            if ($template['key'] === $key) {
                return $template;
            }
        }

        return self::all()[0];
    }

    public static function categories(): array
    {
        return collect(self::all())
            ->pluck('category')
            ->prepend('All')
            ->unique()
            ->values()
            ->all();
    }
}
